(function(){
'use strict';
const $=id=>document.getElementById(id),Q=Quinelings,R=LifeformRenderer,clone=x=>JSON.parse(JSON.stringify(x)),pretty=x=>JSON.stringify(x,null,2),media=matchMedia('(prefers-reduced-motion: reduce)');
const examples=[
 {name:'Share water',text:'allocate 9 L to [{"id":"fern","amount":4},{"id":"sage","amount":7}]',data:{}},
 {name:'Find a route',text:'route A to D in {"A":["B","C"],"B":["D"],"C":["D"],"D":[]} blocked ["B"] | simulate "walk-route"',data:{}},
 {name:'Square & gather',text:'[2,3,5] | square | sum',data:{}},
 {name:'Sort the signal',text:'[8,2,8,4] | dedupe | sort desc | mean',data:{}},
 {name:'Plan a schedule',text:'schedule [{"id":"a","depends":[],"duration":2},{"id":"b","depends":["a"],"duration":3}] s',data:{}},
 {name:'Filter & collect',text:'[1,5,9] L | filter gt 3 | sum',data:{}},
 {name:'Weighted readings',text:'weighted mean [24,36,60] weights [2,1,1] L',data:{},note:'The first reading has twice the weight of each other reading; the result is 36 L.'},
 {name:'Count agreeing sources',text:'consensus [{"source":"a","choice":"yes"},{"source":"b","choice":"yes"}] required 2',data:{},note:'Two supplied source labels agree on yes, meeting the required support of two. Labels do not authenticate witnesses.'},
 {name:'Inspect evidence',text:'evidence [{"source":"a","claim":"safe","value":true}] claim "safe"',data:{},note:'The supplied record supports safe with one source. This calculates evidence state; it does not verify an outside fact.'},
 {name:'Review retry outcomes',text:'retry ["retry","ok"] max 3',data:{},note:'The prepared outcomes complete after two attempts within a cap of three. No work is submitted.'},
 {name:'Blocked route',text:'route A to D in {"A":["B","C"],"B":["D"],"C":["D"],"D":[]} blocked ["B","C"] | simulate "walk-route"',data:{},note:'Closing both intermediate streets leaves no route. Run records a skipped walk proposal with an empty path.'}
];
let artifact=null,compiled=null,projection=null,phase=0,moving=false,mode='body',selected=null,variant=0,records=[],serial=0,generation=0,replayIndex=0,selectedRecord=null,activeRecord=null,dirty=true,last=0,lastDraw=0,visible=true,buildRevision=0;
const perf=[];let pendingProposal=null;
function cancelPending(message){buildRevision++;if(pendingProposal)pendingProposal.abort();pendingProposal=null;$('cancel-proposal').hidden=true;if(message)diagnostic(message);}
function diagnostic(message,error=false){$('diagnostic').textContent=message;$('diagnostic').classList.toggle('error',error);}
function guard(fn){return async(...args)=>{try{return await fn(...args);}catch(error){if(error.name!=='AbortError')diagnostic(error.message,true);return null;}};}
function hash(text){let value=2166136261;for(const c of new TextEncoder().encode(text))value=Math.imul(value^c,16777619)>>>0;return value;}
function cleanGraph(graph){const result=clone(graph);delete result.design;return result;}
function sourceMapRows(map){if(Array.isArray(map))return map.flatMap(row=>row.nodeId?[{nodeId:row.nodeId,clause:row.clause||row.text||row.nodeId}]:Array.isArray(row.nodeIds)?row.nodeIds.map(nodeId=>({nodeId,clause:row.text||row.clause||nodeId})):[]);return [];}
function createArtifact(result,thought,candidate=0){
 const graph=cleanGraph(result.graph),seed=hash(Q.canon(graph)+':candidate:'+candidate),assembly=Anatomy.generate(graph,seed),design=QDL.create('filament');design.anatomy=assembly.anatomy;design.motion.gesture=assembly.gesture;design.composition.yaw=.25;design.composition.pitch=.08;design.composition.lean=-.035;design.chroma.strength=.88;
 const numericOutput=graph.outputs.find(id=>{const type=result.contract?.types?.[id];return type?.kind==='number'||type==='number';});
 if(numericOutput){const type=result.contract.types[numericOutput];design.chroma.lens={kind:'scalar',id:'output',label:'Recorded output',unit:typeof type.unit==='string'?type.unit:'',domain:[0,100],bindings:[{node:numericOutput,path:[]}]};}
 const program=Q.makeTaskProgram(graph,1,design),source=Q.canon(program);Q.encode(program);
 const sourceMap=sourceMapRows(result.sourceMap);for(const row of sourceMap)if(!graph.nodes.some(n=>n.id===row.nodeId))throw Error('Interpretation refers to an unknown operation.');
 return {format:'quineling-artifact',program,source,graph,design,thought,contract:result.contract||null,sourceMap,candidate,interpretation:result.interpretation||{summary:thought,assumptions:result.contract?.assumptions||[]}};
}
function validateProgram(value,metadata={}){
 const program=typeof value==='string'?JSON.parse(value):value,source=Q.canon(program);if(new TextEncoder().encode(source).length>65536)throw Error('Program exceeds the 65,536 byte genome limit.');
 let count=0;function bounded(v,depth=0){if(depth>50||++count>60000)throw Error('Imported program exceeds structural limits.');if(v&&typeof v==='object')for(const x of Object.values(v))bounded(x,depth+1);}bounded(program);
 const shape=Q.describe(program),graph=cleanGraph(shape.graph);if(!shape.design.anatomy)throw Error('This workspace needs a source-authored assembly. Legacy specimens remain in the collection.');
 if(Q.canon(Q.makeTaskProgram(graph,shape.repeats,shape.design))!==source)throw Error('Imported source is not the admitted constructor program.');Q.encode(program);
 const sourceMap=sourceMapRows(metadata.sourceMap);for(const row of sourceMap)if(!graph.nodes.some(n=>n.id===row.nodeId))throw Error('Imported clause refers to an unknown operation.');
 return {format:'quineling-artifact',program:clone(program),source,graph,design:clone(shape.design),thought:typeof metadata.thought==='string'?metadata.thought:'Imported source',contract:metadata.contract||null,sourceMap,candidate:Number.isInteger(metadata.candidate)?metadata.candidate:null,interpretation:{summary:'Recovered source. Original wording is available only when supplied in the companion artifact.',assumptions:[]}};
}
function install(next,options={}){
 const nextCompiled=R.compile(next.graph,next.design);artifact=next;compiled=nextCompiled;phase=0;moving=false;selected=null;replayIndex=0;selectedRecord=null;activeRecord=null;if(!options.copy)generation=0;dirty=true;
 $('portrait-empty').hidden=true;$('lifeform-name').textContent=next.graph.name==='Generated thought'?next.graph.nodes.filter(n=>n.op!=='literal').map(n=>n.op).join(' · '):next.graph.name||'Generated lifeform';$('specimen-count').textContent=`${next.graph.nodes.length} OPERATIONS · ${next.design.anatomy.components.length} PARTS`;$('specimen-status').textContent='READY · NO RESULT YET';$('generation').textContent=options.copy?`VERIFIED GENERATION ${generation}`:'NO EXECUTION YET';$('source').value=next.source;$('source-proof').textContent=`${new TextEncoder().encode(next.source).length.toLocaleString()} canonical source bytes · complete task, anatomy and gesture`;
 for(const id of ['watch','run','export-artifact','export-source','export-wave','export-rgb','recover-wave','recover-rgb'])$(id).disabled=false;$('copy').disabled=true;$('replay').disabled=true;
 $('result').textContent='Ready to run. No result exists for this source.';$('trace').textContent='';$('run-status').textContent='Building and watching do not execute the task.';$('lens-values').textContent='';$('meaning-title').textContent='The built task, made explicit.';$('meaning-summary').textContent=next.interpretation.summary;
 const assumptions=next.interpretation.assumptions||[];if(assumptions.length)$('meaning-summary').textContent+=' '+assumptions.join(' ');
 renderMappings();renderRecords();syncWatch();document.querySelectorAll('[data-variant]').forEach(b=>{b.disabled=next.candidate===null;b.setAttribute('aria-pressed',String(Number(b.dataset.variant)===next.candidate));});
 const gesture=next.design.motion.gesture;$('equations').textContent=`${next.design.anatomy.components.length} source-authored chambers and curved spines. Gesture: ${gesture.kind}; prepare / stroke / recover / rest follow H(z) = 6z⁵ − 15z⁴ + 10z³. Material, crests and operation anchors share each component transform. Attachment sockets define body joints; ordered graph inputs define computation dependencies.`;
 render();
}
function renderMappings(){
 $('clauses').replaceChildren();const groups=new Map();for(const row of artifact.sourceMap){if(!groups.has(row.clause))groups.set(row.clause,[]);groups.get(row.clause).push(row.nodeId);}for(const [clause,ids] of groups){const b=document.createElement('button');b.append(document.createTextNode(clause));const small=document.createElement('small');small.textContent=ids.join(', ');b.append(small);b.dataset.nodes=JSON.stringify(ids);b.onclick=()=>{setMode('program');focus(ids[0]);};$('clauses').append(b);}
 if(!groups.size){const p=document.createElement('p');p.className='help';p.textContent='This source has no accompanying thought map. Inspect its actual operations below.';$('clauses').append(p);}
 $('nodes').replaceChildren();for(const node of artifact.graph.nodes){const b=document.createElement('button');b.textContent=`${node.id} · ${node.op}`;b.dataset.node=node.id;b.onclick=()=>{setMode('program');focus(node.id);};$('nodes').append(b);}
 $('inspection-title').textContent='Select a clause or operation';$('inspection-material').textContent='Each operation owns source-declared material.';$('inspection-detail').textContent='';
}
function focus(id){const node=artifact?.graph.nodes.find(n=>n.id===id);if(!node)return;selected=id;dirty=true;document.querySelectorAll('#nodes button').forEach(b=>{const active=b.dataset.node===id;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});document.querySelectorAll('#clauses button').forEach(b=>b.classList.toggle('active',JSON.parse(b.dataset.nodes).includes(id)));
 const regions=artifact.design.anatomy.owners.filter(o=>o.node===id);$('inspection-title').textContent=`${id} → ${node.op}`;$('inspection-material').textContent=regions.map(r=>`${r.component}: material u ${r.u.map(n=>n.toFixed(3)).join('–')}`).join(' · ');$('inspection-detail').textContent=pretty({operation:node.op,orderedInputs:node.inputs.map((node,port)=>({port,node})),parameters:node.params,outputType:artifact.contract?.types?.[id]||'Source operation; see its recorded value'});}
function setMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));if(mode==='body')selected=null;dirty=true;}
async function build(){
 cancelPending();const revision=buildRevision,text=$('thought').value.trim(),data=JSON.parse($('data').value||'{}');if(!text)throw Error('Describe a supported task first.');if(!data||typeof data!=='object'||Array.isArray(data))throw Error('Supplied data must be a JSON object with named inputs.');diagnostic('Interpreting the complete thought…');
 let proposal=ThoughtCompiler.parse(text),serviceUsed=false;
 const serviceEndpoint=$('service-enabled').checked?$('service-url').value.trim():window.QUINELING_PROPOSAL_ENDPOINT;
 if(Object.keys(data).length&&!serviceEndpoint)throw Error('The local grammar reads data written in the thought. Separate supplied data requires the proposal service or a typed plan.');
 if((proposal.status!=='supported'||Object.keys(data).length)&&serviceEndpoint){
  serviceUsed=true;const controller=new AbortController();pendingProposal=controller;$('cancel-proposal').hidden=false;diagnostic('Requesting a proposed interpretation… Your task will still pass the local compiler.');
  try{const response=await fetch(serviceEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({thought:text,data}),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(130000)])});if(!response.ok)throw Error(`Proposal service returned ${response.status}. Local examples and typed-plan import remain available.`);const body=await response.text();if(body.length>131072)throw Error('Proposal response is too large.');proposal=JSON.parse(body);}
  finally{if(pendingProposal===controller){pendingProposal=null;$('cancel-proposal').hidden=true;}}
 }
 if(revision!==buildRevision)return null;
 if(proposal.status!=='supported'){diagnostic(`${proposal.status||'Unsupported'}: ${(proposal.diagnostics||[]).map(d=>d.message).join(' ')||'This thought needs a supported explicit interpretation.'} No new program was built.`,true);return null;}
 const result=ThoughtCompiler.compile(proposal.intent);if(proposal.sourceMap?.length)result.sourceMap=proposal.sourceMap;if(serviceUsed)result.interpretation={summary:'Service-proposed operations: '+result.graph.nodes.filter(n=>n.op!=='literal').map(n=>n.op).join(' → ')+'. The local compiler checked types, bounds and guards; inspect the program to review its meaning.',assumptions:result.contract.assumptions||[]};variant=0;install(createArtifact(result,text,variant));$('thought-bubble').textContent=text;$('thought-bubble').parentElement.classList.remove('pulse');void $('thought-bubble').offsetWidth;$('thought-bubble').parentElement.classList.add('pulse');diagnostic(`Built ${artifact.graph.nodes.length} operations into a new ${artifact.design.anatomy.components.length}-part body. Ready to run.`);return artifact;
}
function currentRecord(){return records.find(r=>r.id===activeRecord&&r.source===artifact?.source)||null;}
function recordExecution(program,kind,parent=null){const source=Q.canon(program),result=Q.execute(program);if(result.emitted.length!==1||result.emitted[0]!==source)throw Error('Canonical source reproduction failed.');if(parent&&Q.canon(result.tasks.map(t=>t.output))!==Q.canon(parent.result.tasks.map(t=>t.output)))throw Error('Fresh task result differs from its parent.');const record={id:++serial,source,kind,parentRunId:parent?.id||null,result};records.push(record);return record;}
function run(){if(!artifact)throw Error('Build a program first.');const record=recordExecution(artifact.program,'run');activeRecord=record.id;selectedRecord=record.id;replayIndex=0;showRecord(record);$('generation').textContent=`RUN ${record.id} · GENERATION ${generation}`;$('specimen-status').textContent='TASK + SOURCE VERIFIED';$('run-status').textContent=`Run ${record.id} completed ${record.result.tasks.length} task cycle(s); exact source reproduced. Effects: ${record.result.tasks.flatMap(t=>t.effects||[]).length} local simulations.`;$('copy').disabled=false;renderRecords();return record;}
function copy(){const parent=currentRecord();if(!parent)throw Error('Run this source before creating a verified copy.');const source=parent.result.emitted[0],child=validateProgram(JSON.parse(source),artifact),record=recordExecution(child.program,'verified-copy',parent);generation++;child.interpretation=clone(artifact.interpretation);install(child,{copy:true});activeRecord=record.id;selectedRecord=record.id;showRecord(record);renderRecords();$('specimen-status').textContent='FRESH COPY VERIFIED';$('generation').textContent=`VERIFIED GENERATION ${generation}`;$('copy').disabled=false;$('run-status').textContent=`Fresh copy ${generation} executed as run ${record.id}. Source and task outputs match parent run ${parent.id}.`;return record;}
function renderRecords(){const select=$('record-select');select.replaceChildren();if(!records.length){const o=document.createElement('option');o.textContent='No recorded runs';select.append(o);return;}for(const r of records){const o=document.createElement('option');o.value=r.id;o.textContent=`Run ${r.id} · ${r.source===artifact?.source?'current source':'previous source'}`;select.append(o);}if(selectedRecord)select.value=selectedRecord;else select.selectedIndex=-1;}
function showRecord(record){selectedRecord=record.id;$('result').textContent=pretty(record.result.tasks.map(t=>t.output));$('replay').disabled=false;const current=record.source===artifact.source;$('lens-values').textContent=current?'Current source · recorded values':'Previous source · this result does not color the current body.';if(artifact.design.chroma?.lens){const lens=Chroma.resolveLens(artifact.design,record.result.tasks[0],current?'current':'stale');$('lens-values').textContent=lens.entries.map(e=>`${e.node}: ${e.value===undefined?e.status:e.value+' '+lens.lens.unit} · ${e.status} · fixed scale ${lens.lens.domain.join('–')}`).join('\n');}dirty=true;}
function replay(){const record=records.find(r=>r.id===selectedRecord);if(!record)return;const rows=record.result.tasks.flatMap(t=>t.trace);if(!rows.length)return;const row=rows[replayIndex++%rows.length];$('trace').textContent=`Recorded run ${record.id} · operation ${(replayIndex-1)%rows.length+1}/${rows.length}\n${pretty(row)}`;if(record.source===artifact.source)focus(row.edge);}
function candidate(index){cancelPending();if(!artifact||artifact.candidate===null)return;const prior=artifact;variant=index;install(createArtifact({graph:prior.graph,contract:prior.contract,sourceMap:prior.sourceMap,interpretation:prior.interpretation},prior.thought,index));diagnostic('New body selected. Task semantics are unchanged; source identity changed. Previous runs remain in history.');}
function save(name,value){const blob=new Blob([typeof value==='string'?value:pretty(value)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='quineling-'+name+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function waveData(){return {format:'quineling-wave-samples-1',samples:Q.samples(Q.encode(artifact.program))};}
function recover(codec){if(!artifact)return;const restored=codec==='wave'?Q.decode(Q.fromSamples(waveData().samples)):Q.decodeColors(Q.encodeColors(artifact.program));if(Q.canon(restored)!==artifact.source)throw Error('Recovered source differs.');validateProgram(restored,artifact);$('source-proof').textContent=`${codec==='wave'?'65 numerical samples per harmonic band':'Exact RGB byte records'} → canonical source: EXACT. Recovery performed no task execution.`;return restored;}
function importValue(value){cancelPending();let next;if(value?.format==='quineling-intent'){const result=ThoughtCompiler.compile(value);next=createArtifact(result,value.thought||value.name||'Imported typed plan');}else{let program=value,metadata={};if(value?.format==='quineling-artifact'){metadata=value;program=value.source||value.program;}else if(value?.format==='quineling-harmonics-1')program=Q.decode(value);else if(value?.format==='quineling-wave-samples-1')program=Q.decode(Q.fromSamples(value.samples));else if(value?.format==='quineling-chroma-1')program=Q.decodeColors(value);next=validateProgram(program,metadata);}install(next);diagnostic('Imported and validated. The body is still; Run creates a new result.');return next;}
function syncWatch(){$('watch').textContent=moving?'Pause gesture Ⅱ':'Watch gesture ▷';}
function render(){if(!compiled)return;let palette=null;const record=records.find(r=>r.id===selectedRecord);if(mode==='result'&&artifact.design.chroma?.lens){const lens=Chroma.resolveLens(artifact.design,record?.result.tasks[0],record?.source===artifact.source?'current':record?'stale':'not-evaluated');palette=R.paletteFor(artifact.graph,artifact.design,lens);}projection=R.draw($('lifeform'),compiled,phase,{selectedNode:selected,showProgram:mode==='program',palette});perf.push(projection.metrics.renderMs);if(perf.length>600)perf.shift();$('phase').value=Math.round(phase/(Math.PI*2)*1000);$('phase-value').textContent=(phase/(Math.PI*2)).toFixed(2);dirty=false;}
function animate(now){const dt=last?Math.min(.1,(now-last)/1000):0;last=now;if(moving&&visible&&!document.hidden){phase=(phase+dt*Math.PI*2/11)%(Math.PI*2);dirty=true;}if(dirty&&visible&&!document.hidden&&now-lastDraw>=1000/30){render();lastDraw=now;}requestAnimationFrame(animate);}
$('cancel-proposal').onclick=()=>cancelPending('Interpretation cancelled. The displayed program is unchanged.');for(const id of ['thought','data','service-url'])$(id).addEventListener('input',()=>cancelPending('Draft changed. Build to create a program from these words. The displayed specimen still belongs to its previous build.'));$('service-enabled').onchange=()=>cancelPending();
$('build').onclick=guard(build);$('run').onclick=guard(run);$('copy').onclick=guard(copy);$('replay').onclick=replay;$('watch').onclick=()=>{moving=!moving;syncWatch();};$('phase').oninput=()=>{phase=Number($('phase').value)/1000*Math.PI*2;moving=false;syncWatch();dirty=true;};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-variant]').forEach(b=>b.onclick=guard(()=>candidate(Number(b.dataset.variant))));$('record-select').onchange=()=>{const record=records.find(r=>r.id===Number($('record-select').value));if(record)showRecord(record);};$('lifeform').onclick=e=>{if(!projection)return;const rect=e.currentTarget.getBoundingClientRect(),id=R.pick(projection,(e.clientX-rect.left)*e.currentTarget.width/rect.width,(e.clientY-rect.top)*e.currentTarget.height/rect.height);if(id){setMode('program');focus(id);}};
$('export-artifact').onclick=()=>save('artifact',artifact);$('export-source').onclick=()=>save('source',artifact.source);$('export-wave').onclick=()=>save('wave',waveData());$('export-rgb').onclick=()=>save('rgb',Q.encodeColors(artifact.program));$('recover-wave').onclick=guard(()=>recover('wave'));$('recover-rgb').onclick=guard(()=>recover('rgb'));$('import-button').onclick=guard(()=>{const text=$('import-text').value;if(text.length>2000000)throw Error('Import exceeds the two megabyte input limit.');return importValue(JSON.parse(text));});$('import-file').onchange=guard(async()=>{const file=$('import-file').files[0];if(!file)return;if(file.size>2000000)throw Error('Import exceeds the two megabyte input limit.');return importValue(JSON.parse(await file.text()));});
media.addEventListener('change',()=>{moving=false;syncWatch();});document.addEventListener('visibilitychange',()=>last=0);if('IntersectionObserver'in window)new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)dirty=true;},{rootMargin:'100px'}).observe($('lifeform'));
function chooseExample(example){cancelPending();$('thought').value=example.text;$('data').value=pretty(example.data);$('data-origin').textContent='Local examples include their data in the thought. Separate JSON data is sent only to an enabled proposal service. Typed plans carry their own named inputs.';diagnostic('Example loaded. Build constructs its program; Run executes it.'+(example.note?' '+example.note:''));}
for(const example of examples){const b=document.createElement('button');b.textContent=example.name;b.onclick=()=>chooseExample(example);$('examples').append(b);}chooseExample(examples[0]);$('coverage').textContent='Local syntax supports explicit values, allocation, routes, schedules and other bounded tasks; | composes additional operations. Arbitrary English needs a configured proposal service. Unrecognized clauses never become a ready program.';
window.creation={build,run,copy,recover,importValue,candidate,focus,setMode,render,examples,get artifact(){return artifact;},get records(){return records;},get generation(){return generation;},get phase(){return phase;},get moving(){return moving;},get projection(){return projection;},get performance(){return perf.slice();}};requestAnimationFrame(animate);guard(build)();
})();
