import {V1Session,QDLV1Library,VisualCapsule} from './assets/ranch/quinelings-runtime.js';
const $=id=>document.getElementById(id),fields=[1,2,3].map(i=>$('reading-'+i));
const session=new V1Session(),recipe=QDLV1Library.programs.find(p=>p.id==='water-total');
const artifact=session.compile(structuredClone(recipe.intent));
const visual=VisualCapsule.author(artifact.source,artifact.payload.design.anatomy?.seed??1);
const rendered=LifeformRenderer.compile(artifact.payload.task,visual.design),canvas=$('first-creature'),stepCanvas=$('step-creature'),narrow=matchMedia('(max-width:850px)');
const names={readings:'Read the numbers',total:'Add them',count:'Count the readings',summary:'Report the result'};
const explanations={readings:'This step receives the water readings you supplied.',total:'This step adds the readings together.',count:'This step counts how many readings were supplied.',summary:'This step combines the total and count into the answer.'};
let record=null,previousRecord=null,selected=null,phase=0,clock=0,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches;
const metrics={evaluationRequests:0,frames:0,renderMs:[]},visibility=new Map([[canvas,true],[stepCanvas,false]]);
function values(){return fields.map((field,i)=>{const n=field.valueAsNumber;if(field.value.trim()===''||!Number.isFinite(n)||n<0){field.setAttribute('aria-invalid','true');throw Error(`Enter a finite number of zero or greater for reading ${i+1}.`);}field.removeAttribute('aria-invalid');return n;});}
function current(){if(!record)return false;try{return JSON.stringify(values())===JSON.stringify(record.result.bindings.readings);}catch{return false;}}
function occurrence(){return record?.result.occurrences[0];}
function value(id){return occurrence()?.trace.find(row=>row.nodeId===id)?.value;}
function previousValue(id){return previousRecord?.result.occurrences[0].trace.find(row=>row.nodeId===id)?.value;}
function valueText(id){const v=value(id);if(v===undefined)return '';if(id==='readings')return v.join(', ')+' liters';if(id==='total')return v+' liters';if(id==='count')return v+' readings';return v.liters+' liters from '+v.measurements+' readings';}
function paint(forcePreview=false){if(document.hidden)return;for(const [target,visible] of visibility){if((!visible&&!(forcePreview&&target===stepCanvas&&narrow.matches))||(target===stepCanvas&&!selected))continue;const view=LifeformRenderer.draw(target,rendered,phase,{budget:6500,selectedNode:selected,showProgram:!!selected});metrics.frames++;metrics.renderMs.push(view.metrics.renderMs);if(metrics.renderMs.length>120)metrics.renderMs.shift();if(selected&&current()){const anchor=view.anchors.get(selected);if(anchor){const ctx=target.getContext('2d'),text=names[selected]+': '+valueText(selected);ctx.font='16px system-ui';const width=Math.min(target.width-24,ctx.measureText(text).width+20),x=Math.max(12,Math.min(target.width-width-12,anchor.x+12)),y=Math.max(28,Math.min(target.height-24,anchor.y));ctx.fillStyle='#121017ee';ctx.fillRect(x-8,y-22,width,32);ctx.fillStyle='#dcc394';ctx.fillText(text,x,y,width-16);}}}}
function inspect(id){selected=id;for(const button of $('steps').children)button.setAttribute('aria-pressed',String(button.dataset.node===id));$('step-title').textContent=names[id];$('step-description').textContent=explanations[id];$('step-value').textContent=current()?'Calculated value: '+valueText(id)+(id==='total'&&previousRecord&&previousValue(id)!==value(id)?' (previous total: '+previousValue(id)+' liters)':''):'Run the edited readings to see this step’s new value.';$('body-selection').textContent='Highlighted region: '+names[id];paint(true);}
function sync(){const matching=current();if(record){$('answer').hidden=false;$('answer-label').textContent=matching?'Calculated result':'Saved result for earlier readings';const output=occurrence().outputs[0];$('answer-value').textContent=output.liters+' liters from '+output.measurements+' readings';$('answer-context').textContent=matching?(previousRecord&&JSON.stringify(previousRecord.result.bindings.readings)!==JSON.stringify(record.result.bindings.readings)?'The total changed from '+previousRecord.result.occurrences[0].outputs[0].liters+' to '+output.liters+' liters. The instructions and body stayed the same.':'The written instructions added your readings and counted them.'):'This result used '+record.result.bindings.readings.join(', ')+' liters. Your edits have not been calculated.';}if(selected)inspect(selected);else paint();}
function edited(){try{const readings=values();$('readings-line').textContent=readings[0]+', '+readings[1]+' and '+readings[2]+' liters';$('run-status').classList.remove('error');$('run-status').textContent='Readings prepared. Press Run to calculate them.';}catch(error){$('readings-line').textContent='edited readings — please check the numbers';$('run-status').classList.add('error');$('run-status').textContent=error.message+' The last result is kept below.';}$('prediction').hidden=false;$('prediction').textContent='Think about the total you expect, then run the calculation.';$('suggested-change').disabled=fields.every((field,i)=>field.valueAsNumber===i+2);$('change-prompt').textContent='You can use the suggested readings, or open the number fields to try your own. The instructions and body stay the same.';sync();}
$('run-water').onclick=()=>{try{const readings=values();metrics.evaluationRequests++;const next=session.run({artifactId:artifact.id,requestId:'first-water-'+crypto.randomUUID(),inputs:{readings}});const result=next.result.occurrences[0];if(result.status!=='completed')throw Error('The calculation could not finish. Check your readings and try again.');previousRecord=record;record=next;$('prediction').hidden=true;$('change-prompt').textContent=fields.every((field,i)=>field.valueAsNumber===i+2)?'You have tried the suggested readings. Open the number fields to try your own.':'The instructions and body will stay the same. What total would 2, 3 and 4 liters give?';$('run-status').classList.remove('error');$('run-status').textContent='Calculation complete. Select a step to find its region.';$('investigate').hidden=false;$('try-change').hidden=false;sync();inspect(selected??'total');}catch(error){$('run-status').classList.add('error');$('run-status').textContent=error.message;sync();}};
for(const id of Object.keys(names)){const button=document.createElement('button');button.type='button';button.dataset.node=id;button.textContent=names[id];button.setAttribute('aria-pressed','false');button.onclick=()=>inspect(id);$('steps').append(button);}
for(const field of fields){field.setAttribute('aria-describedby','run-status');field.addEventListener('input',edited);}
$('suggested-change').onclick=()=>{fields.forEach((field,i)=>field.value=String(i+2));edited();$('run-water').focus();$('run-water').scrollIntoView({block:'center',behavior:'instant'});};
function motionState(){$('pause-motion').textContent=playing?'Pause motion':'Play motion';$('pause-motion').setAttribute('aria-pressed',String(!playing));}
$('pause-motion').onclick=()=>{playing=!playing;clock=0;motionState();paint();};motionState();
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',event=>{if(event.matches){playing=false;clock=0;motionState();paint();}});
document.addEventListener('visibilitychange',()=>{clock=0;if(!document.hidden)paint();});
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries)visibility.set(entry.target,entry.isIntersecting);clock=0;paint();});observer.observe(canvas);observer.observe(stepCanvas);}
function tick(now){if(playing&&[...visibility.values()].some(Boolean)&&!document.hidden&&now-clock>=1000/30){if(clock)phase=(phase+Math.min(.2,(now-clock)/1000)*.45)%(Math.PI*2);clock=now;paint();}requestAnimationFrame(tick);}paint();requestAnimationFrame(tick);
window.quinelingFirstLesson={metrics,session,artifact,visual,get record(){return record;},get selected(){return selected;},get playing(){return playing;},get phase(){return phase;},isCurrent:current,inspect};
