import {V1Session,QDLV1Library,VisualCapsule} from './assets/ranch/quinelings-runtime.js';
const $=id=>document.getElementById(id),session=new V1Session(),recipe=QDLV1Library.programs.find(p=>p.id==='route-preview'),artifact=session.compile(structuredClone(recipe.intent)),visual=VisualCapsule.author(artifact.source,artifact.payload.design.anatomy?.seed??1),body=LifeformRenderer.compile(artifact.payload.task,visual.design),canvas=$('intro-creature'),preview=$('intro-step-creature');
const places={A:'Home',B:'Bridge',C:'Park',D:'Market'},names={streets:'Read the streets',blocked:'Read closed places',current:'Check the map is current',no:'Withhold an unready walk',route:'Find a route',found:'Check a route exists',ready:'Check the walk is ready',path:'Read the chosen path',proposal:'Propose a walk'};
let inputs={streets:{A:['B','C'],B:['D'],C:['D'],D:[]},blocked:[],current:true},record=null,selected=null,proof=null,phase=0,last=0,moving=!matchMedia('(prefers-reduced-motion: reduce)').matches;
const metrics={taskRequests:0,frames:0},visible=new Map([[canvas,true],[preview,false]]),result=()=>record?.result.occurrences[0],pathText=p=>p.map(id=>places[id]||id).join(' → ');
function valueText(id){const value=result()?.trace.find(row=>row.nodeId===id)?.value;if(value===undefined)return 'Run the task to see this step’s result.';switch(id){case 'streets':return 'Home connects to Bridge and Park; both connect to Market.';case 'blocked':return value.length?'Closed: '+value.map(x=>places[x]||x).join(', '):'No places are closed.';case 'route':return value.found?pathText(value.path):'No route is available.';case 'path':return pathText(value);case 'proposal':return value.status==='simulated'?'Proposed walk: '+pathText(value.payload)+'. Walking is simulated.':'No walk proposed.';default:return value===true?'Yes.':value===false?'No.':JSON.stringify(value);}}
function paint(force=false){if(document.hidden)return;for(const [target,onScreen] of visible){if((!onScreen&&!(force&&target===preview))||(target===preview&&!selected))continue;const view=LifeformRenderer.draw(target,body,phase,{budget:6500,selectedNode:selected,showProgram:!!selected});metrics.frames++;if(selected&&record){const a=view.anchors.get(selected);if(a){const ctx=target.getContext('2d');ctx.font='15px system-ui';const text=names[selected]+': '+valueText(selected),width=Math.min(target.width-20,ctx.measureText(text).width+20),x=Math.max(10,Math.min(target.width-width-10,a.x+10)),y=Math.max(30,Math.min(target.height-24,a.y));ctx.font='15px system-ui';ctx.fillStyle='#121017ee';ctx.fillRect(x-5,y-20,width,30);ctx.fillStyle='#dcc394';ctx.fillText(text,x,y,width-12);}}}}
function inspect(id){if(!names[id])return;selected=id;$('intro-body-selection').textContent='Selected step: '+names[id];$('intro-step-value').textContent=names[id]+': '+valueText(id);for(const button of $('intro-steps').children)button.setAttribute('aria-pressed',String(button.dataset.step===id));paint(true);}
function showMap(){const path=result()?.outputs[0].path||[];for(const road of document.querySelectorAll('[data-road]')){const [from,to]=road.dataset.road.split('-');road.classList.toggle('used',path.some((node,i)=>node===from&&path[i+1]===to));road.classList.toggle('closed',inputs.blocked.includes(from)||inputs.blocked.includes(to));}for(const place of document.querySelectorAll('[data-place]'))place.classList.toggle('closed',inputs.blocked.includes(place.dataset.place));$('intro-map-caption').textContent=inputs.blocked.length?'Bridge closed. The green lines show the route through the park.':'The green lines show the calculated route through the bridge.';}
function run(close=false){try{const nextInputs=structuredClone(inputs);if(close)nextInputs.blocked=['B'];metrics.taskRequests++;const next=session.run({artifactId:artifact.id,requestId:'intro-route-'+crypto.randomUUID(),inputs:nextInputs});if(next.result.occurrences[0].status!=='completed')throw Error('The route calculation did not finish.');inputs=nextInputs;record=next;proof=null;const route=result().outputs[0];$('intro-result').textContent=(close?'The bridge is closed. New route: ':'Calculated route: ')+pathText(route.path)+'.'+(close?' The same instructions found another way.':'');$('intro-inspect').hidden=false;$('intro-close').hidden=false;$('intro-close').disabled=close||inputs.blocked.includes('B');$('intro-copy-result').textContent='';$('intro-save').hidden=true;$('intro-copy-details').hidden=true;showMap();inspect('route');}catch(error){$('intro-result').textContent=error.message;}}
$('intro-run').onclick=()=>run();$('intro-close').onclick=()=>run(true);
for(const id of ['blocked','route','proposal']){const button=document.createElement('button');button.type='button';button.dataset.step=id;button.textContent=names[id];button.setAttribute('aria-pressed','false');button.onclick=()=>inspect(id);$('intro-steps').append(button);}
canvas.onclick=event=>{if(!record)return;const bounds=canvas.getBoundingClientRect(),view=LifeformRenderer.draw(canvas,body,phase,{budget:6500,selectedNode:selected,showProgram:!!selected}),id=LifeformRenderer.pick(view,(event.clientX-bounds.left)*canvas.width/bounds.width,(event.clientY-bounds.top)*canvas.height/bounds.height);if(id)inspect(id);};
$('intro-copy').onclick=()=>{try{if(!record)throw Error('Find a route first.');const emitted=VisualCapsule.verify(visual).source,rebuilt=VisualCapsule.admit(emitted),fresh=new V1Session(),copied=fresh.recover({source:rebuilt.taskSource});if(fresh.exportSnapshot().records.length)throw Error('The fresh copy already has records.');metrics.taskRequests++;const copiedRecord=fresh.run({artifactId:copied.id,requestId:'intro-copy-'+crypto.randomUUID(),inputs:structuredClone(inputs)});if(emitted!==visual.source||copied.source!==artifact.source||JSON.stringify(rebuilt.design)!==JSON.stringify(visual.design)||JSON.stringify(copiedRecord.result.occurrences[0].outputs)!==JSON.stringify(result().outputs))throw Error('The copy differs from the original.');proof={emittedSource:emitted,rebuiltSource:rebuilt.source,originalSource:visual.source,copiedTaskSource:copied.source,originalTaskSource:artifact.source,bodyIdentical:true,freshHistory:true,record:copiedRecord};$('intro-copy-result').textContent='A fresh Quineling rebuilt from its own output. Its complete instructions and body design match. Running it independently gives '+pathText(copiedRecord.result.occurrences[0].outputs[0].path)+'. Save its program to reuse this route planner elsewhere.';$('intro-save').hidden=false;$('intro-copy-details').hidden=false;$('intro-reproduced-source').textContent=emitted;}catch(error){$('intro-copy-result').textContent=error.message;}};
$('intro-save').onclick=()=>{if(!proof)return;const url=URL.createObjectURL(new Blob([JSON.stringify({format:'quineling-artifact',source:proof.emittedSource,thought:'Find a route to the market around closed places.'})],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='route-quineling.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function syncMotion(){$('pause-intro-motion').textContent=moving?'Pause motion':'Play motion';$('pause-intro-motion').setAttribute('aria-pressed',String(!moving));}
$('pause-intro-motion').onclick=()=>{moving=!moving;last=0;syncMotion();paint();};syncMotion();
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',event=>{if(event.matches){moving=false;last=0;syncMotion();paint();}});document.addEventListener('visibilitychange',()=>{last=0;if(!document.hidden)paint();});if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries)visible.set(entry.target,entry.isIntersecting);last=0;paint();});observer.observe(canvas);observer.observe(preview);}
function tick(now){if(moving&&!document.hidden&&[...visible.values()].some(Boolean)&&now-last>=1000/30){if(last)phase=(phase+Math.min(.2,(now-last)/1000)*.45)%(Math.PI*2);last=now;paint();}requestAnimationFrame(tick);}paint();requestAnimationFrame(tick);
window.quinelingIntroduction={artifact,visual,session,metrics,get record(){return record;},get proof(){return proof;},get playing(){return moving;},get phase(){return phase;},get selected(){return selected;}};
