(function(root){
'use strict';
const node=typeof module!=='undefined'&&module.exports;
const Q=node?require('./core.js'):root.Quinelings,T=node?require('./thought.js'):root.ThoughtCompiler;
const A=node?require('./anatomy.js'):root.Anatomy,D=node?require('./qdl.js'):root.QDL;
const C=node?require('./ranch-crypto.js'):root.RanchCrypto;
const TRAITS=Object.freeze(['elongation','spread','curvature','gestureGain','tempo','pigmentGain']);
const POLICIES=Object.freeze({compiler:'quineling-kernels-experimental',assembly:A.COMPILER,heredity:'bounded-traits-experimental',offspring:'closed-four-recipes-experimental',quantization:'ecmascript-round-1e-6-experimental'});
const clone=x=>JSON.parse(JSON.stringify(x)),canon=Q.canon,hash=x=>C.sha256(x),bytes=x=>new TextEncoder().encode(x).length;
function fail(code,path,message){const e=new Error(message);e.code=code;e.path=path;throw e;}
function check(ok,code,path,message){if(!ok)fail(code,path,message);}
function safe(x,path='$',seen=new Set(),depth=0){
 check(depth<=32,'budget',path,'JSON nesting exceeds 32');
 if(x===null||typeof x==='boolean')return;
 if(typeof x==='string'){check(bytes(x)<=2097152,'budget',path,'String exceeds byte budget');return;}
 if(typeof x==='number'){check(Number.isFinite(x),'invalid-input',path,'Expected finite JSON');return;}
 check(x&&typeof x==='object','invalid-input',path,'Expected JSON data');
 check(!seen.has(x),'invalid-input',path,'Cyclic JSON');
 check(Array.isArray(x)?Object.getPrototypeOf(x)===Array.prototype:[Object.prototype,null].includes(Object.getPrototypeOf(x)),'invalid-input',path,'Expected native JSON arrays or plain records');
 const ds=Object.getOwnPropertyDescriptors(x),ks=Reflect.ownKeys(ds);
 check(ks.every(k=>typeof k==='string'),'invalid-input',path,'Symbol properties are not JSON');
 for(const k of ks){const d=ds[k];check(Object.hasOwn(d,'value'),'invalid-input',path+'.'+k,'Accessor properties are not JSON');check(d.enumerable||Array.isArray(x)&&k==='length','invalid-input',path+'.'+k,'Hidden properties are not JSON');}
 if(Array.isArray(x))check(Object.keys(x).length===x.length&&Object.keys(x).every((k,i)=>k===String(i)),'invalid-input',path,'Expected dense JSON array');
 const next=new Set(seen).add(x);for(const k of Object.keys(x)){check(!['__proto__','prototype','constructor'].includes(k),'invalid-input',path+'.'+k,'Unsafe JSON key');safe(ds[k].value,path+'.'+k,next,depth+1);}
}
function closed(x,required,optional=[],path='$'){check(x&&typeof x==='object'&&!Array.isArray(x),'invalid-input',path,'Expected record');for(const k of required)check(Object.hasOwn(x,k),'invalid-input',path+'.'+k,'Missing field');for(const k of Object.keys(x))check(required.includes(k)||optional.includes(k),'invalid-input',path+'.'+k,'Unknown field');}
function str(x,path,max=128){check(typeof x==='string'&&x.length>=1&&x.length<=max,'invalid-input',path,'Expected bounded nonempty string');}
function uint(x,path,max=4294967295){check(Number.isInteger(x)&&x>=0&&x<=max,'invalid-input',path,'Expected bounded unsigned integer');}
function digest(x,path){check(typeof x==='string'&&/^[a-f0-9]{64}$/.test(x),'invalid-input',path,'Expected lowercase SHA256 digest');}
function traits(x,path){closed(x,TRAITS,[],path);for(const k of TRAITS)check(Number.isInteger(x[k])&&Math.abs(x[k])<=1000,'invalid-input',path+'.'+k,'Trait must be an integer in [-1000,1000]');}
function validateInput(input){safe(input);closed(input,['parents','recipe','nonce','style','origin']);check(Array.isArray(input.parents)&&input.parents.length===2,'invalid-input','$.parents','Expected two ordered parents');input.parents.forEach((p,i)=>{closed(p,['artifactId','intentHash'],[],'$.parents.'+i);str(p.artifactId,'$.parents.'+i+'.artifactId');if(p.intentHash!==null)digest(p.intentHash,'$.parents.'+i+'.intentHash');});uint(input.nonce,'$.nonce');
 const r=input.recipe;check(r&&typeof r==='object','invalid-input','$.recipe','Expected recipe');const fields={compose:['donorOutput','recipientInput'],mate:['donorNode','replaceNode'],merge:[],body:['base']};check(Object.hasOwn(fields,r.kind),'invalid-input','$.recipe.kind','Unknown offspring recipe');closed(r,['kind',...fields[r.kind]],[],'$.recipe');for(const k of fields[r.kind])if(k==='base')check(r.base===0||r.base===1,'invalid-input','$.recipe.base','Expected ordered base role');else str(r[k],'$.recipe.'+k,64);
 closed(input.style,['mutation'],['traits'],'$.style');check(['none','gentle'].includes(input.style.mutation),'invalid-input','$.style.mutation','Unknown mutation policy');if(Object.hasOwn(input.style,'traits')){traits(input.style.traits,'$.style.traits');check(input.style.mutation==='none','invalid-input','$.style.mutation','Trait overrides require mutation:none');}
 const o=input.origin;check(o&&typeof o==='object','invalid-input','$.origin','Expected origin');check(['manual','pairing'].includes(o.kind),'invalid-input','$.origin.kind','Unknown origin');closed(o,o.kind==='manual'?['kind']:['kind','worldId','proposalId','parentResidents','epochs'],[],'$.origin');if(o.kind==='pairing'){str(o.worldId,'$.origin.worldId');str(o.proposalId,'$.origin.proposalId');check(Array.isArray(o.parentResidents)&&o.parentResidents.length===2,'invalid-input','$.origin.parentResidents','Expected two residents');o.parentResidents.forEach((s,i)=>str(s,'$.origin.parentResidents.'+i));check(o.parentResidents[0]!==o.parentResidents[1],'self-pairing','$.origin.parentResidents','A resident cannot pair with itself');check(Array.isArray(o.epochs)&&o.epochs.length===2,'invalid-input','$.origin.epochs','Expected two epochs');o.epochs.forEach((n,i)=>uint(n,'$.origin.epochs.'+i,1000000));}return clone(input);
}
function intentHash(intent){if(intent===null||intent===undefined)return null;safe(intent,'$.intent');T.compile(intent);return hash(canon(intent));}
function taskProjection(g){const result=clone(g);delete result.design;return result;}
function parent(p,pin,index){safe(p,'$.parentArtifacts.'+index);check(p&&p.id===pin.artifactId,'parent-pin','$.parents.'+index+'.artifactId','Parent artifact ID mismatch');check(typeof p.source==='string'&&bytes(p.source)<=65536,'source-budget','$.parents.'+index,'Expected source within 64 KiB');let program,shape;try{program=JSON.parse(p.source);shape=Q.describe(program);}catch(e){fail('parent-source','$.parents.'+index,e.message);}
 check(canon(program)===p.source,'parent-source','$.parents.'+index,'Parent source is not canonical');check(Array.isArray(shape.graph.nodes),'parent-source','$.parents.'+index,'Offspring requires a task constructor');const graph=taskProjection(shape.graph);let rebuilt;try{rebuilt=Q.makeTaskProgram(graph,shape.repeats,shape.design);}catch(e){fail('parent-source','$.parents.'+index,e.message);}check(canon(rebuilt)===p.source,'parent-source','$.parents.'+index,'Parent is not a complete canonical constructor');check(p.id==='ql_'+hash(p.source),'parent-pin','$.parents.'+index+'.artifactId','Artifact ID does not identify the exact source');
 const ih=intentHash(p.intent||null);check(ih===pin.intentHash,'parent-pin','$.parents.'+index+'.intentHash','Parent intent pin mismatch');let compiled;if(p.intent){compiled=T.compile(p.intent);check(canon(compiled.graph)===canon(graph),'companion-mismatch','$.parents.'+index,'Companion does not reproduce source task graph');}return {id:p.id,source:p.source,sourceHash:hash(p.source),intentHash:ih,graph,design:clone(shape.design),repeats:shape.repeats,compiled,intent:p.intent?clone(p.intent):null,sourceMap:clone(p.sourceMap||compiled?.sourceMap||[])};
}
function topo(g){const done=new Set(),pending=g.nodes.slice(),out=[];while(pending.length){const i=pending.findIndex(n=>n.inputs.every(id=>done.has(id)));check(i>=0,'cycle','$.graph','Graph is not acyclic');const n=pending.splice(i,1)[0];done.add(n.id);out.push(n);}return out;}
function closure(g,ids){const map=new Map(g.nodes.map(n=>[n.id,n])),out=new Set();function visit(id){check(map.has(id),'selector','$.recipe','Unknown selected node '+id);if(out.has(id))return;out.add(id);map.get(id).inputs.forEach(visit);}ids.forEach(visit);return out;}
function protectedNodes(g){const out=new Set();for(const n of g.nodes)if(n.op==='action'){out.add(n.id);for(const id of closure(g,[n.inputs[0]]))out.add(id);}return out;}
function normalizedTask(g,repeats){const ns=topo(g),ids=new Map(ns.map((n,i)=>[n.id,i]));return {repeats,nodes:ns.map(n=>({op:n.op,inputs:n.inputs.map(id=>ids.get(id)),params:n.params})),outputs:g.outputs.map(id=>ids.get(id))};}
function resolvedBody(design,graph){const d=clone(design);delete d.heredity;if(d.anatomy){delete d.anatomy.seed;delete d.anatomy.compiler;const ids=new Map(topo(graph).map((n,i)=>[n.id,i]));for(const o of d.anatomy.owners)o.node=ids.get(o.node);}return d;}
function assembleTask(ps,r,diagnostics){
 if(r.kind==='body'){const b=ps[r.base];return {graph:clone(b.graph),intent:b.intent?clone(b.intent):null,compiled:b.compiled?clone(b.compiled):null,sourceMap:clone(b.sourceMap),repeats:b.repeats,origins:b.graph.nodes.map(n=>({nodeId:n.id,parent:r.base,parentNodeId:n.id}))};}
 check(ps.every(p=>p.compiled),'missing-companion','$.parents','Task recipes require both typed companions');check(ps[0].sourceHash!==ps[1].sourceHash,'same-source','$.parents','Task recipes require distinct source parents');
 const maps=ps.map((p,role)=>new Map(topo(p.graph).map((n,i)=>[n.id,'p'+role+'n'+i]))),origins=[],types={};let nodes=[],outputs,seam;
 function imported(role,keep){return topo(ps[role].graph).filter(n=>!keep||keep.has(n.id)).map(n=>{const id=maps[role].get(n.id);origins.push({nodeId:id,parent:role,parentNodeId:n.id});types[id]=ps[role].compiled.contract.types[n.id];return {...clone(n),id,inputs:n.inputs.map(x=>maps[role].get(x))};});}
 if(r.kind==='merge'){const ports=ps.flatMap(p=>p.graph.outputs);check(ports.length<=16,'ports','$.recipe','Merge report exceeds 16 input ports');nodes=[...imported(0),...imported(1)];nodes.push({id:'report',op:'report',inputs:ps.flatMap((p,i)=>p.graph.outputs.map(x=>maps[i].get(x))),params:{labels:ps.flatMap((p,i)=>p.graph.outputs.map((_,j)=>(i?'b':'a')+j))}});origins.push({nodeId:'report',parent:'generated'});outputs=['report'];}
 else{const donor=r.kind==='compose'?r.donorOutput:r.donorNode,recipient=r.kind==='compose'?r.recipientInput:r.replaceNode,donorNode=ps[0].graph.nodes.find(n=>n.id===donor),recipientNode=ps[1].graph.nodes.find(n=>n.id===recipient);
 check(donorNode&&recipientNode,'selector','$.recipe','Unknown selected donor or recipient node');if(r.kind==='compose'){check(ps[0].graph.outputs.includes(donor),'selector','$.recipe.donorOutput','Compose donor must be a declared output');check(recipientNode.op==='literal','selector','$.recipe.recipientInput','Compose recipient must be a literal');}
 check(!protectedNodes(ps[1].graph).has(recipient),'protected-guard','$.recipe','Action nodes and guard ancestors are protected');const keep=closure(ps[0].graph,[donor]);check(ps[0].graph.nodes.filter(n=>keep.has(n.id)).every(n=>n.op!=='action'),'impure-donor','$.recipe','Donor predecessor closure must be pure');const dt=ps[0].compiled.contract.types[donor],rt=ps[1].compiled.contract.types[recipient];check(canon(dt)===canon(rt),'unit-type','$.recipe','Connection requires equal complete normalized types');
 const donorId=maps[0].get(donor),replaceId=maps[1].get(recipient);nodes=[...imported(0,keep),...imported(1)];nodes=nodes.filter(n=>n.id!==replaceId).map(n=>({...n,inputs:n.inputs.map(x=>x===replaceId?donorId:x)}));outputs=ps[1].graph.outputs.map(x=>x===recipient?donorId:maps[1].get(x));const live=closure({nodes},outputs);nodes=nodes.filter(n=>live.has(n.id));
 for(const old of ps[1].graph.nodes.filter(n=>n.op==='action')){const now=nodes.find(n=>n.id===maps[1].get(old.id));check(now&&canon(now.params)===canon(old.params)&&now.inputs[0]===maps[1].get(old.inputs[0]),'protected-guard','$.recipe','All recipient actions and guards must survive');for(const guardId of closure(ps[1].graph,[old.inputs[0]])){const before=ps[1].graph.nodes.find(n=>n.id===guardId),after=nodes.find(n=>n.id===maps[1].get(guardId));check(after&&canon(after)===canon({...before,id:maps[1].get(guardId),inputs:before.inputs.map(x=>maps[1].get(x))}),'protected-guard','$.recipe','Recipient guard cone changed');}}
 const downstream=new Set([donorId]);for(const n of topo({nodes}))if(n.inputs.some(x=>downstream.has(x)))downstream.add(n.id);const integration=nodes.find(n=>n.id.startsWith('p1n')&&n.op!=='literal'&&downstream.has(n.id)&&closure({nodes},outputs).has(n.id));check(integration,'disconnected-integration','$.recipe','Donation must feed surviving original recipient computation and output');seam={donorNode:donorId,recipientNode:replaceId,type:clone(dt),integrationNode:integration.id};
 }
 check(nodes.length<=64,'node-budget','$.recipe','Child exceeds 64 nodes');nodes=topo({nodes});const liveIds=new Set(nodes.map(n=>n.id));const liveOrigins=origins.filter(o=>liveIds.has(o.nodeId));const name='Ranch '+r.kind+' offspring',intent={format:'quineling-intent',name,thought:'Generated '+r.kind+' recipe over ordered source parents.',inputs:nodes.filter(n=>n.op==='literal').map(n=>({id:n.id,value:clone(n.params.value),type:clone(types[n.id])})),steps:nodes.filter(n=>n.op!=='literal'),outputs,assumptions:[]};
 const compiled=T.compile(intent);diagnostics.push({code:'repeats-reset',path:'$.recipe',message:'Task-changing recipes use one task repeat.'});return {graph:compiled.graph,intent,compiled,sourceMap:compiled.sourceMap,repeats:1,origins:compiled.graph.nodes.map(n=>liveOrigins.find(o=>o.nodeId===n.id)),seam};
}
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),quant=x=>Math.round(x*1e6)/1e6||0;
function parentTraits(p){if(p.design.heredity)return {label:'authored-heredity',traits:clone(p.design.heredity.traits)};const cs=p.design.anatomy?.components||[],rootPart=cs.find(c=>c.parent===null);check(rootPart,'missing-anatomy','$.parents','Legacy phenotype requires authored assembly anatomy');const e=rootPart.kind==='chamber'?2*rootPart.axes[1]:rootPart.length,r=rootPart.kind==='chamber'?2*Math.sqrt(rootPart.axes[0]*rootPart.axes[2]):rootPart.radii[0]+rootPart.radii[1],spines=cs.filter(c=>c.kind==='spine'),b=spines.length?spines.reduce((s,c)=>s+c.bend[0],0)/spines.length:0;const values=[1000*(e/r-1.5)/1.5,1000*(r/e-.6)/.6,5000*b,1000*((p.design.motion.gesture?.strength??.65)-.65)/.35,1000*(p.design.motion.phaseRate-.038)/.007,1000*((p.design.chroma?.strength??0)-.85)/.1];return {label:'legacy-phenotype',traits:Object.fromEntries(TRAITS.map((k,i)=>[k,clamp(Math.round(values[i]),-1000,1000)]))};}
function inherit(ps,style,seed){const parents=ps.map(parentTraits),draw=label=>parseInt(hash(seed+'\n'+label).slice(0,8),16),draws=[],changes=[];let ts;if(style.traits)ts=clone(style.traits);else{ts={};for(const k of TRAITS){const n=draw('trait:'+k)%3,a=parents[0].traits[k],b=parents[1].traits[k];ts[k]=n===0?a:n===1?b:Math.floor((a+b)/2);draws.push({trait:k,selection:['A','B','floor-midpoint'][n],value:ts[k]});}if(style.mutation==='gentle'){const first=draw('mutation:locus:0')%6,remaining=TRAITS.filter((_,i)=>i!==first),chosen=[TRAITS[first],remaining[draw('mutation:locus:1')%5]];chosen.forEach((k,i)=>{const n=draw('mutation:delta:'+i),delta=(n%2===0?1:-1)*(1+n%80),before=ts[k];ts[k]=clamp(before+delta,-1000,1000);changes.push({trait:k,requestedDelta:delta,actualDelta:ts[k]-before,saturated:before+delta!==ts[k]});});}}
 return {traits:ts,parents,draws,changes,override:!!style.traits};}
function authoredDesign(ps,task,r,seedDigest,genetics,nonce,diagnostics){const base=r.kind==='body'?r.base:1,d=clone(ps[base].design);delete d.heredity;const fresh=A.generate(task.graph,parseInt(seedDigest.slice(0,8),16));d.anatomy=fresh.anatomy;d.motion.gesture=fresh.gesture;const g=k=>genetics.traits[k]/1000;
 for(const c of d.anatomy.components)if(c.kind==='spine'){c.length=quant(clamp(c.length*(1+.12*g('elongation')),.12,1.2));c.radii=c.radii.map(x=>quant(clamp(x*(1+.10*g('spread')),.015,.16)));c.bend[0]=quant(clamp(c.bend[0]+.025*g('curvature'),-.2,.2));}else{c.axes[1]=quant(clamp(c.axes[1]*(1+.12*g('elongation')),.04,.35));for(const i of [0,2])c.axes[i]=quant(clamp(c.axes[i]*(1+.10*g('spread')),.04,.35));}
 d.motion.gesture.strength=quant(clamp(.65+.10*g('gestureGain'),0,1));d.motion.phaseRate=quant(clamp(.038+.007*g('tempo'),0,.05));d.chroma.strength=quant(clamp(.85+.10*g('pigmentGain'),0,1));
 if(d.chroma.lens){try{D.validateBindings(d,task.graph);}catch{delete d.chroma.lens;diagnostics.push({code:'dropped-lens',path:'$.child.design.chroma.lens',message:'Inherited scalar lens is incompatible with child task references.'});}}
 d.heredity={model:POLICIES.heredity,parents:ps.map(p=>p.sourceHash),seedDigest,nonce,traits:clone(genetics.traits)};D.validateBindings(d,task.graph);A.validateOwners(d.anatomy,task.graph);A.validateGesture(d.motion.gesture);return d;
}
function constructor(graph,repeats,design){try{return Q.makeTaskProgram(graph,repeats,design);}catch(e){fail(/source.*(?:exceeds|budget)/i.test(e.message)?'source-budget':'offspring-refused','$.child.source',e.message);}}
function build(parents,input){try{input=validateInput(input);safe(parents,'$.parentArtifacts');check(Array.isArray(parents)&&parents.length===2,'invalid-input','$.parentArtifacts','Expected two detached artifacts');const ps=parents.map((p,i)=>parent(p,input.parents[i],i)),diagnostics=[],task=assembleTask(ps,input.recipe,diagnostics),key={domain:'quineling-ranch-construction-experimental',parents:ps.map(p=>({sourceHash:p.sourceHash,intentHash:p.intentHash})),recipe:clone(input.recipe),style:clone(input.style),nonce:input.nonce,policies:clone(POLICIES)},candidateId='qc_'+hash(canon(key)),seedDigest=hash('quineling-ranch-seed-experimental\n'+canon(key)),genetics=inherit(ps,input.style,seedDigest),design=authoredDesign(ps,task,input.recipe,seedDigest,genetics,input.nonce,diagnostics),program=constructor(task.graph,task.repeats,design),source=canon(program);check(bytes(source)<=65536,'source-budget','$.child.source','Complete source exceeds 64 KiB');const childSourceHash=hash(source),id='ql_'+childSourceHash,derivationId='qd_'+hash(canon({candidateId,childSourceHash,origin:input.origin})),base=ps[input.recipe.kind==='body'?input.recipe.base:1];const changes={sourceChanged:source!==base.source,taskSyntaxChanged:canon(normalizedTask(task.graph,task.repeats))!==canon(normalizedTask(base.graph,base.repeats)),bodyChanged:canon(resolvedBody(design,task.graph))!==canon(resolvedBody(base.design,base.graph))};check(changes.taskSyntaxChanged||changes.bodyChanged,'no-novelty','$.recipe','Candidate changes neither executable task nor resolved body');const classification=input.recipe.kind==='body'?(ps[0].sourceHash===ps[1].sourceHash?'same-source body variation':'body-only inheritance'):changes.taskSyntaxChanged?'task-and-body offspring':'body variation';
 const child={id,source,program,graph:clone(task.graph),design,sourceMap:clone(task.sourceMap),harmonics:Q.encode(program),colors:Q.encodeColors(program)};if(task.intent){child.intent=clone(task.intent);child.contract=clone(task.compiled.contract);}const lineage={id:derivationId,candidateId,childArtifactId:id,childSourceHash,parents:key.parents,construction:clone(input),policies:clone(POLICIES),classification,changes:clone(changes),origins:clone(task.origins),heredity:genetics};if(task.seam)lineage.seam=task.seam;check(bytes(canon(lineage))<=32768,'lineage-budget','$.lineage','Derivation exceeds 32 KiB');const candidate={candidateId,derivationId,childSourceHash,child,changes,classification,diagnostics,lineage};check(bytes(canon(candidate))<=2097152,'candidate-budget','$','Candidate exceeds 2 MiB');return candidate;
 }catch(e){if(!e.code)e.code='offspring-refused';if(!e.path)e.path='$';throw e;}}
const api={POLICIES,TRAITS,validateInput,intentHash,build};if(node)module.exports=api;root.QuinelingOffspring=api;
})(typeof globalThis!=='undefined'?globalThis:this);
