import {Runtime,Quinelings as Q,QuinelingOffspring as O,QuinelingWorld as W} from './assets/ranch/quinelings-runtime.js';
import {RanchRenderer} from './ranch-renderer.js';
const $=id=>document.getElementById(id),pretty=x=>JSON.stringify(x,null,2),media=matchMedia('(prefers-reduced-motion: reduce)'),runtime=new Runtime();
const specimens=[
 ['Reservoir','mean [10,20,30] L'],['Waterkeeper','budget 5 for 12 L'],
 ['Gatherer','[2,3,4] | square | sum | report total'],['Signal','[8,2,8,4] | dedupe | sort desc | mean'],
 ['Sieve','[1,5,9] L | filter gt 3 | sum'],['Estimator','weighted mean [24,36,60] weights [2,1,1] L'],
 ['Pathfinder','route A to D in {"A":["B","C"],"B":["D"],"C":["D"],"D":[]} blocked ["B"] | simulate "walk-route"'],
 ['Planner','schedule [{"id":"a","depends":[],"duration":2},{"id":"b","depends":["a"],"duration":3}] s'],
 ['Council','consensus [{"source":"a","choice":"yes"},{"source":"b","choice":"yes"}] required 2'],['Witness','evidence [{"source":"a","claim":"safe","value":true}] claim "safe"']
];
const artifacts=new Map(),names=new Map(),records=new Map(),ceremonies=[],shown=new Set();let world,selectedResident=null,selectedArtifact=null,selectedNode=null,phase=0,dirty=true,last=0,lastDraw=0,lastSocial=0,moving=false,social=false,busy=false,candidate=null,candidateInput=null,foreground=null,anchors=null;
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
const guard=fn=>async(...args)=>{try{return await fn(...args);}catch(e){status(`${e.code?e.code+': ':''}${e.message}`,true);return null;}};
function pause(){moving=false;social=false;$('gestures').checked=false;$('social').checked=false;last=0;lastSocial=0;dirty=true;}
function refresh(){world=runtime.worldInspect(world.id);dirty=true;renderWorld();}
function command(command){const result=runtime.worldCommand({worldId:world.id,expectedRevision:world.revision,sequence:world.nextSequence,command});refresh();return result;}
function name(id){return names.get(id)||'New Quineling';}
function residentState(r){if(r.nurseryUntil>world.tick)return '◇ NURSERY';if(r.pendingProposal)return '✧ PROPOSAL READY';if(r.partner)return '↔ PAIRED';if(r.rest)return 'Ⅱ RESTING';if(r.invitation)return '↗ INVITING';return r.enabled?'○ PARTICIPATING':'○ QUIET ADULT';}
function renderWorld(){
 $('garden').classList.toggle('dense',world.residents.length>12);
 $('world-state').textContent=`${world.residents.length} residents · ${world.tick} social ticks`;
 const labels=$('resident-labels');labels.replaceChildren();const box=$('garden').getBoundingClientRect(),scale=Math.min(box.width/512,box.height/320),ox=(box.width-512*scale)/2,oy=(box.height-320*scale)/2;
 for(const r of world.residents){const p=document.createElement('div');p.className='resident-label'+(foreground?.pinned.parentResidents.includes(r.id)?' parent':'')+(r.id===selectedResident?' selected':'')+(r.nurseryUntil>world.tick?' nursery':'');p.style.left=(ox+r.x*scale)/box.width*100+'%';p.style.top=(oy+r.y*scale)/box.height*100+'%';p.style.transform=`translate(-50%, ${r.y>260?-24*scale-(innerWidth<700?12:26):24*scale}px)`;p.append(document.createTextNode(name(r.artifactId)));const state=document.createElement('span');state.textContent=residentState(r);p.append(state);labels.append(p);}
 const links=$('social-links');links.replaceChildren();for(const r of world.residents){const partner=r.partner||r.invitation?.partnerId;if(!partner||r.id>partner)continue;const other=world.residents.find(a=>a.id===partner);if(!other)continue;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',r.x);line.setAttribute('y1',r.y);line.setAttribute('x2',other.x);line.setAttribute('y2',other.y);if(r.partner)line.classList.add('pair');links.append(line);}const list=$('residents');const focused=document.activeElement?.dataset.resident;list.replaceChildren();for(const r of world.residents){const b=document.createElement('button');b.className='resident-card';b.dataset.resident=r.id;b.setAttribute('aria-pressed',String(r.id===selectedResident));const title=document.createElement('strong');title.textContent=name(r.artifactId);const small=document.createElement('small');small.textContent=`${residentState(r)} · ${artifacts.get(r.artifactId)?.graph.nodes.length||'?'} ops · energy ${r.energy}`;b.append(title,small);b.onclick=()=>select(r.id);list.append(b);if(focused===r.id)b.focus({preventScroll:true});}
 const nursery=world.residents.filter(r=>r.nurseryUntil>world.tick);$('nursery').textContent=nursery.length?nursery.map(r=>`${name(r.artifactId)} · matures at tick ${r.nurseryUntil}; participation off`).join('\n'):'No children in the nursery. Imported residents are adults.';
 const current=world.residents.find(r=>r.id===selectedResident);$('participate').checked=current?.enabled||false;$('participate').disabled=!current||busy||current.nurseryUntil>world.tick;
 renderProposals();
}
function select(residentId){const r=world.residents.find(r=>r.id===residentId);if(!r)return;selectedResident=residentId;inspect(r.artifactId);renderWorld();}
function inspect(artifactId){selectedArtifact=artifactId;selectedNode=null;const a=artifacts.get(artifactId)||runtime.inspect(artifactId);artifacts.set(a.id,a);$('resident-name').textContent=name(a.id);$('resident-meta').textContent=`${a.graph.nodes.length} operations · ${a.design.anatomy.components.length} body components · ${a.design.motion.gesture.kind} gesture`;$('thought').textContent=a.intent?.thought||'Recovered source. No original thought accompanies this artifact.';$('source').textContent=a.source;$('program-count').textContent=`${a.graph.outputs.length} declared output(s)`;$('owner-detail').textContent='Select an operation to illuminate its owned tissue and actual input connections.';$('node-detail').textContent='';
 $('nodes').replaceChildren();for(const n of a.graph.nodes){const b=document.createElement('button');b.dataset.node=n.id;b.textContent=`${symbol(n.op)} ${n.id} · ${n.op}`;b.setAttribute('aria-pressed','false');b.onclick=()=>focus(n.id);$('nodes').append(b);}
 $('clauses').replaceChildren();for(const row of a.sourceMap){const b=document.createElement('button');b.textContent=row.clause;b.dataset.node=row.nodeId;b.setAttribute('aria-pressed','false');b.onclick=()=>focus(row.nodeId);$('clauses').append(b);}if(!a.sourceMap.length){const p=document.createElement('p');p.className='help';p.textContent='No supplied thought map. The operations below come from the actual source.';$('clauses').append(p);}showRecord();showLineage(a.id);dirty=true;
}
function symbol(op){return op==='literal'?'○':op==='report'?'□':op==='action'?'⚑':op==='bfs'?'↗':'◇';}
function focus(id){const a=artifacts.get(selectedArtifact),n=a.graph.nodes.find(n=>n.id===id);if(!n)return;selectedNode=id;for(const b of document.querySelectorAll('#nodes button,#clauses button'))b.setAttribute('aria-pressed',String(b.dataset.node===id));const owners=a.design.anatomy.owners.filter(o=>o.node===id);$('owner-detail').textContent=`${id} owns ${owners.map(o=>`${o.component}, u ${o.u.map(x=>x.toFixed(3)).join('–')}`).join('; ')}. Lines in the portrait show ordered program dependencies.`;$('node-detail').textContent=pretty({node:id,operation:n.op,orderedInputs:n.inputs.map((node,port)=>({port,node,type:a.contract?.types?.[node]||'No companion type'})),parameters:n.params,outputType:a.contract?.types?.[id]||'No companion type',declaredOutput:a.graph.outputs.includes(id)});dirty=true;}
function showRecord(){const r=records.get(selectedArtifact);$('run-state').textContent=r?`Fresh run ${r.id.slice(0,16)} · source reproduced exactly`:'No recorded result.';$('result').textContent=r?pretty(r.result.tasks.map(t=>({outputs:t.output,simulatedEffects:t.effects}))):'Run creates a fresh execution record. Preview and admission create none.';}
function showLineage(id){$('lineage').replaceChildren();const rows=runtime.lineage({artifactId:id,limit:32}).derivations;if(!rows.length){$('lineage').textContent='No derivation recorded in this session. Source heredity assertions alone are not verified ancestry.';return;}for(const d of rows){const p=document.createElement('article');p.textContent=`${d.classification} · ${d.id}\nOrdered parents: ${d.parents.map(x=>x.artifactId||x.sourceHash).join(' → ')}\n${d.origins.length} node origins · recipe ${d.input?.recipe?.kind||d.construction?.recipe?.kind||'recorded'}`;$('lineage').append(p);const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent='Inspect the actual derivation receipt';pre.className='code';pre.textContent=pretty(d);details.append(summary,pre);$('lineage').append(details);}}
function option(value,text){const o=document.createElement('option');o.value=value;o.textContent=text;return o;}
function updateParents(){const oldA=$('parent-a').value,oldB=$('parent-b').value;for(const id of ['parent-a','parent-b']){$(id).replaceChildren();for(const a of artifacts.values())$(id).append(option(a.id,name(a.id)));}if(artifacts.has(oldA))$('parent-a').value=oldA;if(artifacts.has(oldB))$('parent-b').value=oldB;else $('parent-b').selectedIndex=Math.min(1,artifacts.size-1);updateSelectors();}
function typeText(a,id){const t=a.contract?.types?.[id];return t?pretty(t).replace(/\s+/g,' ').replace(/"/g,''):'no companion type';}
function updateSelectors(){candidate=null;candidateInput=null;$('admit').disabled=true;const a=artifacts.get($('parent-a').value),b=artifacts.get($('parent-b').value),recipe=$('recipe').value;if(!a||!b)return;$('donor').replaceChildren();$('recipient').replaceChildren();for(const n of a.graph.nodes)if(recipe==='mate'||a.graph.outputs.includes(n.id))$('donor').append(option(n.id,`${n.id} · ${n.op} · ${typeText(a,n.id)}`));for(const n of b.graph.nodes)if(recipe==='mate'||n.op==='literal')$('recipient').append(option(n.id,`${n.id} · ${n.op} · ${typeText(b,n.id)}`));$('connection-fields').hidden=recipe==='merge'||recipe==='body';$('candidate-status').textContent='Prepare again after changing parents, selectors or style.';$('candidate-portrait').hidden=true;$('candidate-detail').textContent='';}
function pins(a){return {artifactId:a.id,intentHash:O.intentHash(a.intent||null)};}
function construction(origin={kind:'manual'},parents=null,recipe=null){const a=artifacts.get(parents?.[0]||$('parent-a').value),b=artifacts.get(parents?.[1]||$('parent-b').value),kind=$('recipe').value;return {parents:[pins(a),pins(b)],recipe:recipe||(kind==='compose'?{kind,donorOutput:$('donor').value,recipientInput:$('recipient').value}:kind==='mate'?{kind,donorNode:$('donor').value,replaceNode:$('recipient').value}:kind==='body'?{kind,base:1}:{kind}),nonce:Number($('nonce').value),style:{mutation:$('mutation').value},origin};}
function preview(input=construction()){const response=runtime.offspringPreview(input);candidateInput=input;if(response.status!=='ready'){candidate=null;$('admit').disabled=true;$('candidate-status').textContent='Construction refused: '+response.diagnostics.map(d=>d.message).join(' ');$('candidate-detail').textContent=pretty(response.diagnostics);$('candidate-portrait').hidden=true;return null;}candidate=response.candidate;const a=candidate.child;const f=runtime.offspringFrame({input,candidateId:candidate.candidateId,childSourceHash:candidate.childSourceHash,phase:0,options:{budget:4000,crests:2}});drawCandidate(a,f.frame);$('candidate-status').textContent=`${candidate.classification} · ${a.graph.nodes.length} operations · preview only, no run`;$('candidate-detail').textContent=pretty({candidateId:candidate.candidateId,sourceHash:candidate.childSourceHash,changes:candidate.changes,diagnostics:candidate.diagnostics,typedSeam:candidate.lineage.seam||null,origins:candidate.lineage.origins});$('admit').disabled=input.origin.kind!=='manual';return candidate;}
function drawCandidate(a,f){const canvas=$('candidate-portrait'),ctx=canvas.getContext('2d');canvas.hidden=false;ctx.clearRect(0,0,280,280);let lo=[Infinity,Infinity],hi=[-Infinity,-Infinity];for(let i=0;i<f.points.length;i+=4){for(let j=0;j<2;j++){lo[j]=Math.min(lo[j],f.points[i+j]);hi[j]=Math.max(hi[j],f.points[i+j]);}}const s=Math.min(230/(hi[0]-lo[0]||1),230/(hi[1]-lo[1]||1));for(let i=0;i<f.owners.length;i++){ctx.fillStyle=f.nodeColors[f.owners[i]];ctx.globalAlpha=.16;ctx.beginPath();ctx.arc(140+(f.points[i*4]-(lo[0]+hi[0])/2)*s,140+(f.points[i*4+1]-(lo[1]+hi[1])/2)*s,1.8,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}
function admitLibrary(){if(!candidate||candidateInput.origin.kind!=='manual')throw Error('Prepare a manual candidate first.');const ack=runtime.offspringAdmit({input:candidateInput,candidateId:candidate.candidateId,childSourceHash:candidate.childSourceHash,target:{kind:'library'},requestId:'ui-library-'+crypto.randomUUID()});const child=runtime.inspect(ack.artifactId);artifacts.set(child.id,child);names.set(child.id,'Library offspring '+artifacts.size);updateParents();selectedResident=null;inspect(child.id);$('participate').disabled=true;status(`Saved ${ack.derivationId} to the library. No task executed; no meadow birth occurred.`);return ack;}
function originFor(p){return {kind:'pairing',worldId:world.id,proposalId:p.id,parentResidents:[...p.parentResidents],epochs:[...p.epochs]};}
function renderProposals(){const host=$('proposals');host.replaceChildren();for(const p of world.proposals){const row=document.createElement('div');row.className='proposal';const rs=p.parentResidents.map(id=>world.residents.find(r=>r.id===id));row.append(document.createTextNode(`Courtship proposal: ${rs.map(r=>name(r.artifactId)).join(' + ')} · expires tick ${p.expiry}. No child yet.`));const prepare=document.createElement('button');prepare.textContent='Prepare this pair';prepare.onclick=guard(()=>{const ids=rs.map(r=>r.artifactId);$('parent-a').value=ids[0];$('parent-b').value=ids[1];updateSelectors();preview(construction(originFor(p),ids));renderProposals();status('Proposal-bound candidate prepared. Admission still rechecks the live parents.');});const admit=document.createElement('button');admit.textContent='Admit nursery child';admit.disabled=!candidate||candidateInput?.origin?.proposalId!==p.id;admit.onclick=guard(()=>admitWorld(p));const cancel=document.createElement('button');cancel.textContent='Cancel proposal';cancel.onclick=guard(()=>command({kind:'cancelProposal',proposalId:p.id}));row.append(prepare,admit,cancel);host.append(row);}}
function admitWorld(p){if(!candidate||candidateInput?.origin?.proposalId!==p.id)throw Error('Prepare this exact proposal first.');const pinned=structuredClone({candidate,input:candidateInput,parentResidents:p.parentResidents});const ack=runtime.offspringAdmit({input:candidateInput,candidateId:candidate.candidateId,childSourceHash:candidate.childSourceHash,target:{kind:'world',worldId:world.id,expectedRevision:world.revision},requestId:'ui-birth-'+crypto.randomUUID()});const child=runtime.inspect(ack.artifactId);artifacts.set(child.id,child);names.set(child.id,'Reservoir sprout '+(artifacts.size-10));refresh();updateParents();select(ack.residentId);queueCeremony(ack,pinned);status(`Nursery admission acknowledged: ${ack.derivationId}. The parents remain present. No task executed.`);return ack;}
function queueCeremony(ack,pinned){if(shown.has(ack.derivationId))return;shown.add(ack.derivationId);const item={ack,pinned,remaining:6};if(media.matches||renderer.lost){settle(item);return;}if(ceremonies.length>=8){settle(item);return;}ceremonies.push(item);nextCeremony();}
function nextCeremony(){if(foreground||!ceremonies.length)return;foreground=ceremonies.shift();renderWorld();$('ceremony').hidden=false;$('ceremony-title').textContent='Two thoughts. One new Quineling.';$('ceremony-detail').textContent=`Receipt ${foreground.ack.derivationId.slice(0,20)}… · admission placed child ${foreground.ack.residentId} in the nursery at tick ${foreground.ack.tick}. Parents ${foreground.pinned.parentResidents.join(' + ')} remain in the garden.`;}
function settle(item=foreground){if(!item)return;if(foreground===item){foreground=null;$('ceremony').hidden=true;}dirty=true;renderWorld();nextCeremony();}
function settleAll(){ceremonies.length=0;settle();}
async function familyDemo(){if(busy)return;busy=true;pause();$('family-demo').disabled=true;try{const [a,b]=world.residents.slice(0,2);if(!a||!b)throw Error('Two founding parents are required.');status('Inviting Reservoir and Waterkeeper through the real world protocol…');for(const r of [a,b])if(!r.enabled)command({kind:'participate',residentId:r.id,enabled:true});command({kind:'invite',residentId:a.id,partnerId:b.id});command({kind:'invite',residentId:b.id,partnerId:a.id});let proposal;for(let i=0;i<180;i++){command({kind:'advance',ticks:4});proposal=world.proposals.find(p=>p.parentResidents.includes(a.id)&&p.parentResidents.includes(b.id));if(proposal&&proposal.parentResidents.every(id=>world.residents.find(r=>r.id===id).energy>=50))break;if(i%8===0){status(`Actual courtship · tick ${world.tick}; waiting for a fresh, eligible proposal.`);await new Promise(resolve=>setTimeout(resolve,0));}}if(!proposal)throw Error('The bounded courtship attempt made no proposal. Guard congestion can prevent pairing; inspect the residents and try explicit invitations.');const parents=proposal.parentResidents.map(id=>world.residents.find(r=>r.id===id).artifactId),donor=artifacts.get(parents[0]),recipient=artifacts.get(parents[1]);let recipe;if(donor.id===a.artifactId){recipe={kind:'compose',donorOutput:donor.graph.outputs[0],recipientInput:recipient.graph.nodes.find(n=>n.op==='literal'&&n.id.includes('available'))?.id||recipient.graph.nodes.find(n=>n.op==='literal').id};}else recipe={kind:'merge'};if(!preview(construction(originFor(proposal),parents,recipe)))throw Error('The actual recipe was refused. Inspect the candidate diagnostics.');admitWorld(proposal);}finally{busy=false;$('family-demo').disabled=false;renderWorld();}}
function save(name,value){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:pretty(value)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='quineling-'+name+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const renderer=new RanchRenderer($('meadow'),runtime,s=>{$('render-status').textContent=s;});renderer.onLoss=()=>{pause();settleAll();};renderer.onRestore=()=>{pause();dirty=true;};renderer.onPrewarm=()=>{dirty=true;};
function render(){$('motion-note').replaceChildren(document.createTextNode(moving||social?'A LIVING GARDEN':'A QUIET GARDEN'),document.createElement('br'));const note=document.createElement('small');note.textContent=`GESTURES ${moving?'ON':'OFF'} · SOCIAL TIME ${social?'ON':'OFF'}`;$('motion-note').append(note);renderer.draw(world,artifacts,phase,{selectedResident,selectedNode,moving});if(selectedArtifact)anchors=renderer.detail($('portrait'),artifacts.get(selectedArtifact),phase,selectedNode);dirty=false;}
function animate(now){const dt=last?Math.min(.1,(now-last)/1000):0;last=now;if(!document.hidden){if(moving&&!media.matches){phase=(phase+dt*Math.PI*2/12)%(Math.PI*2);dirty=true;}if(social&&!busy&&now-lastSocial>250){lastSocial=now;try{command({kind:'advance',ticks:4});}catch(e){pause();status(e.message,true);}}if(foreground&&moving){foreground.remaining-=dt;if(foreground.remaining<=0)settle();}if(world&&dirty&&now-lastDraw>=1000/24){render();lastDraw=now;}renderer.prewarm();}requestAnimationFrame(animate);}
$('gestures').onchange=()=>{moving=$('gestures').checked;if(media.matches&&moving){moving=false;$('gestures').checked=false;status('Reduced motion is enabled. The complete garden remains still.');}dirty=true;};$('social').onchange=()=>{social=$('social').checked;lastSocial=performance.now();status(social?'Social time advances in explicit four-tick command batches. Participation is separately controlled per resident.':'Social time paused.');};$('pause').onclick=()=>{pause();status('All view and social clocks paused.');};$('step').onclick=guard(()=>{command({kind:'advance',ticks:4});status(`Advanced to tick ${world.tick}. No task executed.`);});$('family-demo').onclick=guard(familyDemo);$('participate').onchange=guard(()=>{command({kind:'participate',residentId:selectedResident,enabled:$('participate').checked});status($('participate').checked?'Resident may participate in courtship.':'Resident participation withdrawn.');});$('run').onclick=guard(()=>{const record=runtime.run(selectedArtifact);records.set(selectedArtifact,record);$('session-note').textContent='LOCAL SESSION · FRESH RESULT RECORDED';showRecord();status('Fresh task executed. Exact constructor source reproduced; any effects are local simulations.');});$('preview').onclick=guard(()=>{preview();renderProposals();});$('admit').onclick=guard(admitLibrary);for(const id of ['parent-a','parent-b','recipe','mutation','donor','recipient','nonce'])$(id).onchange=id==='donor'||id==='recipient'||id==='nonce'?()=>{candidate=null;candidateInput=null;$('admit').disabled=true;renderProposals();}:updateSelectors;
$('skip-ceremony').onclick=()=>settle();$('meadow').onclick=e=>{if(foreground)return;const rect=e.currentTarget.getBoundingClientRect(),id=renderer.pick((e.clientX-rect.left)*e.currentTarget.width/rect.width,(e.clientY-rect.top)*e.currentTarget.height/rect.height);if(id)select(id);};$('portrait').onclick=e=>{if(!anchors)return;const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)*360/rect.width,y=(e.clientY-rect.top)*360/rect.height;let id=null,d=28*28;for(const [node,p]of anchors){const dd=(p[0]-x)**2+(p[1]-y)**2;if(dd<d){d=dd;id=node;}}if(id)focus(id);};
$('export-source').onclick=()=>save('source',artifacts.get(selectedArtifact).source);$('export-genome').onclick=()=>save('harmonics',artifacts.get(selectedArtifact).harmonics);$('recover').onclick=guard(()=>{const a=artifacts.get(selectedArtifact),recovered=runtime.recover({harmonics:a.harmonics});if(recovered.source!==a.source)throw Error('Genome recovery changed source.');status('Harmonic genome → exact complete source. Recovery performed no task execution.');});$('import').onchange=guard(async()=>{const file=$('import').files[0];if(!file)return;if(file.size>2097152)throw Error('Recovery file exceeds two MiB.');const v=JSON.parse(await file.text()),input=typeof v==='string'?{source:v}:Array.isArray(v)?{source:JSON.stringify(v)}:v.format==='quineling-harmonics-1'?{harmonics:v}:v.format==='quineling-chroma-1'?{colors:v}:v.source?{source:v.source}:null;if(!input)throw Error('Supply canonical constructor source JSON or a harmonic/color genome.');const a=runtime.recover(input);artifacts.set(a.id,a);names.set(a.id,'Recovered resident');const ack=command({kind:'import',artifactId:a.id});updateParents();select(ack.residentId);status('Recovered source imported as a quiet adult. No absent thought, units, verified ancestry or task result was invented.');});
media.addEventListener('change',()=>{pause();settleAll();status('Motion preference changed. All clocks paused.');});document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();settleAll();}else{last=0;dirty=true;status('Welcome back. View and social time remain paused.');}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){pause();settleAll();status('All clocks paused; ceremony settled to its already committed child.');}});window.addEventListener('resize',()=>{if(world)renderWorld();dirty=true;});
function habitat(){const svg=$('habitat'),ns='http://www.w3.org/2000/svg';const add=(kind,attrs)=>{const e=document.createElementNS(ns,kind);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);svg.append(e);return e;};W.CLEARINGS.forEach((slots,i)=>{const x=(slots[0].x+slots[1].x)/2,y=slots[0].y;add('ellipse',{cx:x,cy:y,rx:59,ry:29});add('ellipse',{cx:x,cy:y,rx:63,ry:33,class:'outer'});for(const slot of slots){add('circle',{cx:slot.x,cy:y+25,r:1});}const text=add('text',{x,y:y+39,'text-anchor':'middle'});text.textContent=['I · WILLOW COURT','II · FERN COURT','III · SAGE COURT','IV · REED COURT'][i];});for(const [x,y,sign]of [[231,230,-1],[282,228,1],[238,112,-1],[276,110,1]]){for(let i=0;i<7;i++){const yy=y-i*5;add('path',{d:`M ${x} ${y} Q ${x+sign*6} ${yy-9} ${x+sign*7} ${yy-18}`,class:'petal'});add('path',{d:`M ${x+sign*4} ${yy} Q ${x+sign*15} ${yy-4} ${x+sign*15} ${yy-9} Q ${x+sign*7} ${yy-9} ${x+sign*4} ${yy}`,class:'petal'});}}}
function start(){habitat();world=runtime.worldCreate({worldKey:'the-quineling-garden',seed:20261004});for(let i=0;i<specimens.length;i++){const [label,thought]=specimens[i],result=runtime.create(thought,{seed:170+i*7919});if(result.status!=='supported')throw Error(`Founding thought ${label}: ${result.diagnostics.map(d=>d.message).join(' ')}`);artifacts.set(result.artifact.id,result.artifact);names.set(result.artifact.id,label);command({kind:'import',artifactId:result.artifact.id});}updateParents();select(world.residents[0].id);status('Ten different source-backed residents. Gestures, participation and social time are off. No tasks have run.');$('render-status').textContent=renderer.mode==='WebGL2'?'Shared WebGL2 · ≤32,000 tissue samples · ≤8 gesturing residents.':'Canvas fallback · 16 MiB pose cache · ≤8 moving residents · six bins.';render();}
window.ranch={runtime,artifacts,names,renderer,command,refresh,select,focus,preview,admitWorld,familyDemo,pause,settleAll,get world(){return world;},get candidate(){return candidate;},get phase(){return phase;},get moving(){return moving;},get social(){return social;},get ceremonies(){return {foreground,queued:ceremonies.length};},get records(){return records;}};
guard(start)();requestAnimationFrame(animate);
