const assert=require('node:assert/strict'),fs=require('node:fs'),D=require('./qdl.js'),Q=require('./core.js');
const checks=[];function test(name,fn){fn();checks.push(name);}
test('All ten families are bounded valid QDL expressions',()=>{assert.equal(new Set(D.FAMILIES).size,10);for(const family of D.FAMILIES)assert(D.validate(D.create(family)));});
test('Unknown syntax, families and models are rejected',()=>{for(const mutate of [d=>d.extra=1,d=>d.family='eval',d=>d.organ.model='execute',d=>d.filament.model='lookup',d=>d.motion.clock='execution',d=>d.motion.reducedMotion='ignore']){const d=D.create();mutate(d);assert.throws(()=>D.validate(d));}});
test('Unbounded geometry and invalid density hierarchy are rejected',()=>{for(const mutate of [d=>d.organ.amplitudes=[.8,.4],d=>d.motion.phaseRate=Infinity,d=>d.filament.bend=10,d=>d.framing.scale=1,d=>d.ink.ghostAlpha=d.ink.ridgeAlpha,d=>d.organ.baseRadius=0]){const d=D.create();mutate(d);assert.throws(()=>D.validate(d));}});
test('Validated radial envelope is positive across sampled opcodes and phase',()=>{const d=D.create();for(let frequency=1;frequency<=Q.OPS.length;frequency++)for(let j=0;j<100;j++){const n={frequency,indegree:4,outdegree:8,params:{value:6}},r=D.organRadius(d,n,j*.071,j*.213);assert(r>0&&Number.isFinite(r));}});
test('Pinned-sine offset vanishes at both endpoint samples',()=>{for(let frequency=1;frequency<=80;frequency++)for(const t of [0,.5,3,8]){assert(Math.abs(D.filamentBend(D.DEFAULT,frequency,0,t))<1e-12);assert(Math.abs(D.filamentBend(D.DEFAULT,frequency,1,t))<1e-12);}});
test('Species and mapping parameters survive quine and both genomes',()=>{for(const family of D.FAMILIES){const p=Q.makeTaskProgram({version:1,name:'design fixture',nodes:[{id:'n',op:'literal',inputs:[],params:{value:1}}],outputs:['n']},1,D.create(family));const run=Q.execute(p);assert.equal(run.emitted[0],Q.canon(p));const child=JSON.parse(run.emitted[0]);assert.equal(Q.describe(child).design.family,family);assert.equal(Q.describe(Q.decode(Q.encode(p))).design.family,family);assert.equal(Q.describe(Q.decodeColors(Q.encodeColors(p))).design.family,family);}});
test('Design-only edits preserve task output while changing encoded source',()=>{const graph={version:1,name:'sum',nodes:[{id:'n',op:'literal',inputs:[],params:{value:[2,3]}},{id:'s',op:'sum',inputs:['n'],params:{}}],outputs:['s']},a=Q.makeTaskProgram(graph,1,D.create('seed')),b=Q.makeTaskProgram(graph,1,D.create('moth'));assert.notEqual(Q.canon(a),Q.canon(b));assert.deepEqual(Q.execute(a).tasks[0].output,Q.execute(b).tasks[0].output);});
test('Invalid source-embedded design is rejected before task execution',()=>{const p=Q.makeTaskProgram({version:1,name:'invalid design',nodes:[{id:'n',op:'literal',inputs:[],params:{value:1}}],outputs:['n']});function corrupt(x){if(Array.isArray(x))x.forEach(corrupt);else if(x&&typeof x==='object'&&x.design)x.design.motion.clock='execution';}corrupt(p);assert.throws(()=>Q.execute(p));});
fs.writeFileSync(__dirname+'/design-verification.json',JSON.stringify({passed:checks.length,checks,numericalGeometry:'sampled floating-point checks, not a theorem'},null,2)+'\n');console.log(JSON.stringify({passed:checks.length,checks},null,2));
