'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs');
const V=require('./qdl-v1.js'),Q=require('./core.js'),T=require('./qdl-v1-types.js'),C=require('./qdl-v1-contract.js'),D=require('./qdl.js');
const N=(unit='one')=>({kind:'number',unit}),A=element=>({kind:'array',element}),B={kind:'boolean'},S={kind:'string'};
let passed=0;const check=(name,fn)=>{fn();passed++;console.log('✓ '+name);};
const refusal=(fn,code)=>assert.throws(fn,e=>e.code===code);
const recipe=(overrides={})=>({format:'qdl-intent',version:1,name:'Water total',thought:'Sum supplied water readings.',inputs:[{id:'water',name:'readings',type:A(N('L'))}],steps:[{id:'total',op:'sum',inputs:['water'],params:{}}],outputs:['total'],...overrides});
const p=V.compile(recipe()),source=Q.canon(p),a=V.admit(source);
check('two supplied snapshots change result/input identity, never source or body',()=>{
 const x=V.execute(p,{readings:[2,3,4]}),y=V.execute(p,{readings:[5,6]});assert.deepEqual(x.occurrences[0].outputs,[9]);assert.deepEqual(y.occurrences[0].outputs,[11]);assert.notEqual(x.inputHash,y.inputHash);assert.equal(x.sourceHash,y.sourceHash);assert.equal(x.emitted[0],source);assert.equal(y.emitted[0],source);assert.deepEqual(Q.describe(p).design,a.payload.design);assert.deepEqual(Q.execute(p,{bindings:{readings:[2,3,4]}}),x);
});
check('source carries declarations, every node type, normalized units and pins',()=>{assert(source.includes('Sum supplied water readings.'));assert(source.includes('"unit":"L"'));assert.equal(a.payload.registryDigest,V.registryDigest);assert.equal(a.payload.task.nodes.every(n=>n.type),true);assert.equal(a.sourceHash,'ql_'+crypto.createHash('sha256').update(source).digest('hex'));});
check('source-only constructor verification needs no run inputs',()=>{refusal(()=>V.execute(p),'missing-input');const proof=V.verifyQuine(p);assert.equal(proof.source,source);assert(proof.constructorSteps>0);});
check('three executed fresh generations preserve complete source declarations and both genomes',()=>{let program=p;for(let i=0;i<3;i++){const run=V.execute(program,{readings:[2,3,4]});assert.equal(run.emitted[0],source);program=V.admit(run.emitted[0]).program;assert.equal(V.admit(Q.decode(Q.encode(program))).source,source);assert.equal(V.admit(Q.decodeColors(Q.encodeColors(program))).source,source);}});
check('missing/extra/type-invalid bindings refuse before evaluation',()=>{refusal(()=>V.execute(p,{}),'missing-input');refusal(()=>V.execute(p,{readings:[],total:7}),'unknown-field');refusal(()=>V.execute(p,{readings:['2']}),'type');refusal(()=>V.execute(p,{readings:[Infinity]}),'nonfinite');});
check('source pin/profile/canonical constructor edits refuse',()=>{for(const [key,value,code]of[['registryDigest','0'.repeat(64),'unsupported-registry'],['canonical','other','identity'],['version',2,'identity']]){const payload=structuredClone(a.payload);payload[key]=value;refusal(()=>V.admit(Q.makePayloadProgram(payload,1)),code);}const edited=structuredClone(p);edited[2][1][2][1][1]=2;refusal(()=>V.admit(edited),'identity');});
check('noncanonical source and duplicate object keys refuse',()=>{refusal(()=>V.admit(JSON.stringify(p,null,2)),'identity');const duplicate=source.replace('"version":1','"version":1,"version":1');refusal(()=>V.admit(duplicate),'identity');});
check('runtime values never enter recovered source',()=>{const run=V.execute(p,{readings:[12.3456789]});assert(!run.emitted[0].includes('12.3456789'));assert.equal(V.admit(Q.decode(Q.encode(p))).payload.thought.tasks[0].text,'Sum supplied water readings.');});
check('authored observations/evidence/goals/decisions/plans resolve typed references',()=>{
 const graph=V.compile(recipe({steps:[{id:'total',op:'sum',inputs:['water'],params:{}},{id:'enough',op:'compare',inputs:['total'],params:{operator:'gte',value:8}}],outputs:['total','enough']}));const base=V.admit(graph).payload;
 base.thought={observations:[{id:'seen',text:'Supplied readings',input:'water',path:[],basis:'testimony'}],evidence:[{id:'ev',claim:'enough water',source:'authored',observation:'seen',value:true}],goals:[{id:'goal',text:'Have enough water',outputs:['total','enough'],completion:'enough'}],decisions:[{id:'decision',text:'Assess quantity',guard:'enough',evidence:['ev']}],plans:[{id:'plan',text:'Assess the supplied snapshot',tasks:['assessment']}],tasks:[{id:'assessment',text:'Sum and compare',nodes:['water','total','enough'],outputs:['total','enough']}]};
 const authored=V.build({name:base.name,thought:base.thought,task:base.task,design:base.design});assert.deepEqual(V.execute(authored,{readings:[2,3,4]}).occurrences[0].outputs,[9,true]);assert.deepEqual(V.admit(Q.decodeColors(Q.encodeColors(authored))).payload.thought,base.thought);
 for(const mutate of [t=>t.evidence[0].observation='absent',t=>t.goals[0].completion='total',t=>t.observations[0].path=['nope'],t=>t.tasks[0].nodes=['total','enough'],t=>t.decisions[0].evidence=['absent'],t=>t.plans[0].tasks=['absent'],t=>t.tasks[0].id='seen']){const thought=structuredClone(base.thought);mutate(thought);refusal(()=>V.build({name:base.name,thought,task:base.task,design:base.design}),'reference');}
});
check('computed failures retain completed trace, publish no staged simulations or output',()=>{
 const intent={format:'qdl-intent',version:1,name:'Staged repair',thought:'Simulate a guarded repair, then compute the mean.',inputs:[{id:'guard',value:true,type:B},{id:'payload',value:'lamp',type:S},{id:'readings',name:'readings',type:A(N())}],steps:[{id:'action',op:'action',inputs:['guard','payload'],params:{allowed:true,action:'repair'}},{id:'mean',op:'mean',inputs:['readings'],params:{}},{id:'out',op:'report',inputs:['action','mean'],params:{labels:['receipt','mean']}}],outputs:['out'],repeats:3};
 const program=V.compile(intent),run=V.execute(program,{readings:[]});assert.equal(run.status,'failed');assert.equal(run.occurrences.length,1);const occurrence=run.occurrences[0];assert.deepEqual(occurrence.effects,[]);assert.deepEqual(occurrence.outputs,[]);assert.equal(occurrence.diagnostic.nodeId,'mean');assert.equal(occurrence.diagnostic.occurrence,0);assert(occurrence.trace.some(x=>x.op==='action'&&x.value.status==='simulated'));assert.equal(run.emitted[0],Q.canon(program));
 const good=V.execute(program,{readings:[2,4]});assert.equal(good.occurrences.length,3);assert(good.occurrences.every(o=>o.effects.length===1&&o.outputs[0].mean===3));
});
check('intermediate floating overflow and signed-safe-integer overflow fail before output',()=>{
 let run=V.execute(p,{readings:[1e308,1e308,-1e308]});assert.equal(run.status,'failed');assert.equal(run.occurrences[0].diagnostic.code,'nonfinite');
 const integer={...N('L'),integer:true};const q=V.compile(recipe({inputs:[{id:'water',name:'readings',type:A(integer)}]}));run=V.execute(q,{readings:[Number.MAX_SAFE_INTEGER,1,-1]});assert.equal(run.status,'failed');assert.equal(run.occurrences[0].diagnostic.code,'refinement');
});
check('dynamic result refinements produce explicit failures',()=>{const q=V.compile(recipe({steps:[{id:'total',op:'sum',inputs:['water'],params:{},type:{...N('L'),max:5}}]}));const run=V.execute(q,{readings:[3,4]});assert.equal(run.status,'failed');assert.equal(run.occurrences[0].diagnostic.code,'refinement');assert.equal(run.occurrences[0].trace.length,1);});
check('trace amplification stays bounded and returns a useful failure record',()=>{
 const steps=[];let previous='value';for(let i=0;i<60;i++){const id='copy'+i;steps.push({id,op:'choose',inputs:['flag',previous,'value'],params:{}});previous=id;}
 const q=V.compile({format:'qdl-intent',version:1,name:'Amplification guard',thought:'Select repeatedly over supplied data.',inputs:[{id:'flag',value:true,type:B},{id:'value',name:'value',type:S}],steps,outputs:[previous],repeats:8});const run=V.execute(q,{value:'x'.repeat(16384)});assert(Buffer.byteLength(JSON.stringify(run))<=V.RUN_LIMIT);assert.equal(run.status,'failed');assert.equal(run.occurrences.at(-1).diagnostic.code,'limit');assert.deepEqual(run.occurrences.at(-1).outputs,[]);assert(run.occurrences[0].trace.length>0);assert.equal(run.emitted[0],Q.canon(q));
});
check('new opcodes have distinct append-only exact colors and body roles',()=>{const ops=['input','arithmetic','compareValues','all','select','evidenceFresh','reconcile'];assert.equal(Q.OPS.indexOf('input'),34);assert.equal(new Set(Q.COLORS).size,Q.COLORS.length);for(const op of ops)assert.equal(Q.instructionFromColor(Q.instructionColor(op)),op);});
check('legacy source constructors still execute under their original profile',()=>{const task={version:1,nodes:[{id:'value',op:'literal',inputs:[],params:{value:3}}],outputs:['value']};const q=Q.makeTaskProgram(task,1,D.create());assert.equal(V.isProgram(q),false);assert.deepEqual(Q.execute(q).tasks[0].output,[3]);refusal(()=>V.admit(q),'identity');});
fs.writeFileSync('research/qdl-v1/runtime-verification.json',JSON.stringify({checkedAt:new Date().toISOString(),node:process.version,passed,registryDigest:V.registryDigest,sourceHash:a.sourceHash,scope:'Candidate source/type/input/declaration/constructor/failure/budget integration; no adapter, physical GPU or full JS refinement claim.'},null,2)+'\n');
console.log('Passed '+passed+' v1 source/runtime integration groups.');
