(function(root){
'use strict';
const node=typeof module!=='undefined'&&module.exports,Q=node?require('./core.js'):root.Quinelings,V=node?require('./qdl-v1.js'):root.QDLV1,D=node?require('./qdl.js'):root.QDL,W=node?require('./woven-body.js'):root.WovenBody;
const clone=x=>JSON.parse(JSON.stringify(x));
function validateDesign(design,graph){const base=clone(design);delete base.woven;D.validateBindings(base,graph);if(!design.woven||design.anatomy)throw Error('Visual capsule requires only its experimental body');W.validate(design.woven,graph);return true;}
function task(source){const program=JSON.parse(source);if(Q.canon(program)!==source)throw Error('Task source must be canonical');if(V.isProgram(program)){const a=V.admit(source);return {program,graph:a.payload.task,stable:true};}const shape=Q.describe(program);if(Q.canon(Q.makeTaskProgram(shape.graph,shape.repeats,shape.design))!==source)throw Error('Task is not an admitted constructor');return {program,graph:shape.graph,stable:false};}
function build(taskSource,design){const payload={format:'quineling-visual-capsule',profile:'woven-experimental',taskSource,design};return admit(Q.canon(Q.makePayloadProgram(payload,1)));}
function author(taskSource,seed=1){const t=task(taskSource),design=D.create();Object.assign(design.composition,{yaw:0,pitch:0,lean:0});design.woven=W.author(t.graph,seed);design.chroma.strength=.35;return build(taskSource,design);}
function admit(source){if(typeof source!=='string'||new TextEncoder().encode(source).length>65536)throw Error('Visual capsule must be canonical source up to 64 KiB');const program=JSON.parse(source);let payload;function visit(t){if(!Array.isArray(t)||t[0]==='quote')return;if(t[0]==='run'&&t[1]?.[0]==='quote'){visit(t[1][1]);return;}if(t[0]==='task'&&t[1]?.[0]==='quote')payload=t[1][1];else for(const x of t.slice(1))visit(x);}visit(program);if(!payload||payload.format!=='quineling-visual-capsule'||payload.profile!=='woven-experimental'||Object.keys(payload).sort().join(',')!=='design,format,profile,taskSource')throw Error('Unsupported visual capsule');const t=task(payload.taskSource);validateDesign(payload.design,t.graph);if(Q.canon(Q.makePayloadProgram(payload,1))!==source)throw Error('Visual capsule constructor does not match its source');return {source,program:clone(program),taskSource:payload.taskSource,task:t.graph,stable:t.stable,design:clone(payload.design)};}
function verify(capsule){const a=admit(capsule.source),copy=Q.execute(a.program,{constructionOnly:true});if(copy.emitted[0]!==a.source)throw Error('Visual constructor emission differs');return {exactSource:true,source:copy.emitted[0],constructorSteps:copy.steps};}
function recover(capsule,encoding){const decoded=encoding==='harmonics'?Q.decode(Q.encode(capsule.program)):encoding==='colors'?Q.decodeColors(Q.encodeColors(capsule.program)):null;if(!decoded)throw Error('Unknown genome encoding');const recovered=admit(Q.canon(decoded));if(recovered.source!==capsule.source)throw Error('Visual genome differs');return recovered;}
function isCapsule(program){try{admit(Q.canon(program));return true;}catch{return false;}}
function makeTaskProgram(graph,repeats=1,design){if(!design?.woven)return Q.makeTaskProgram(graph,repeats,design);const base=clone(design);delete base.woven;const clean=clone(graph);delete clean.design;return build(Q.canon(Q.makeTaskProgram(clean,repeats,base)),design).program;}
function describe(program){if(!isCapsule(program))return Q.describe(program);const a=admit(Q.canon(program)),s=Q.describe(JSON.parse(a.taskSource));return {...s,graph:{...s.graph,design:clone(a.design)},design:clone(a.design)};}
function execute(program,options){if(!isCapsule(program))return Q.execute(program,options);if(options!==undefined){if(!options||typeof options!=='object'||Array.isArray(options)||Object.getPrototypeOf(options)!==Object.prototype||Object.keys(options).some(k=>!['constructionOnly','bindings'].includes(k))||('constructionOnly'in options&&typeof options.constructionOnly!=='boolean')||(options.constructionOnly===true&&'bindings'in options))throw Error('Invalid visual execution options');if('bindings'in options&&(!options.bindings||typeof options.bindings!=='object'||Array.isArray(options.bindings)))throw Error('Invalid visual bindings');}const a=admit(Q.canon(program)),proof=verify(a);if(options?.constructionOnly)return {emitted:[proof.source],tasks:[],trace:[],steps:proof.constructorSteps};const result=Q.execute(JSON.parse(a.taskSource),options);return {...result,taskSourceEmitted:result.emitted,emitted:[proof.source],steps:(result.steps??result.constructorSteps??0)+proof.constructorSteps,taskProfile:a.stable?'qdl-v1':'legacy'};}
const api={author,build,admit,verify,recover,validateDesign,isCapsule,makeTaskProgram,describe,execute,runtime:{...Q,makeTaskProgram,describe,execute}};if(node)module.exports=api;root.VisualCapsule=api;
})(typeof globalThis!=='undefined'?globalThis:this);
