import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {Runtime,QuinelingError,type Artifact,type OffspringInput,type WorldAction,type World} from '../src/index.js';
import {OffspringInputSchema,WorldCommandSchema,AdmissionSchema} from '../src/schema.js';
const require=createRequire(import.meta.url),O=require('../../../offspring.js'),Q=require('../../../core.js'),K=require('../../../kernels.js');
const code=(expected:string)=>(e:unknown)=>e instanceof QuinelingError&&e.code===expected;
function parents(r:Runtime){const make=(thought:string)=>{const x=r.create(thought);if(x.status!=='supported')throw Error(thought);return x.artifact;};return [make('mean [10,20,30] L'),make('budget 5 for 12 L')] as [Artifact,Artifact];}
function input(a:Artifact,b:Artifact):OffspringInput {return {parents:[{artifactId:a.id,intentHash:O.intentHash(a.intent)},{artifactId:b.id,intentHash:O.intentHash(b.intent)}],recipe:{kind:'compose',donorOutput:a.graph.outputs[0]!,recipientInput:b.graph.nodes.find(n=>n.op==='literal'&&n.params.value===5)!.id},nonce:17,style:{mutation:'none'},origin:{kind:'manual'}};}
function ready(r:Runtime,i:OffspringInput){const p=r.offspringPreview(i);assert.equal(p.status,'ready');if(p.status!=='ready')throw Error(JSON.stringify(p));return p.candidate;}
function cmd(r:Runtime,w:World,c:WorldAction){r.worldCommand({worldId:w.id,expectedRevision:w.revision,sequence:w.nextSequence,command:c});return r.worldInspect(w.id);}
function proposal(r:Runtime,a:Artifact,b:Artifact){let w=r.worldCreate({worldKey:'fixtures',seed:17});w=cmd(r,w,{kind:'import',artifactId:a.id});w=cmd(r,w,{kind:'import',artifactId:b.id});for(const resident of w.residents)w=cmd(r,w,{kind:'participate',residentId:resident.id,enabled:true});w=cmd(r,w,{kind:'invite',residentId:w.residents[0]!.id,partnerId:w.residents[1]!.id});w=cmd(r,w,{kind:'invite',residentId:w.residents[1]!.id,partnerId:w.residents[0]!.id});for(let n=0;n<180&&!w.proposals.length;n++)w=cmd(r,w,{kind:'advance',ticks:4});assert.equal(w.proposals.length,1);for(let n=0;n<100&&w.residents.some(x=>x.energy<50);n++)w=cmd(r,w,{kind:'advance',ticks:4});return w;}

test('offspring preview/frame/admission are passive; independent source runs and copies useful child',()=>{
 const r=new Runtime({maxRecords:1}),[a,b]=parents(r),i=input(a,b);let runs=0,actions=0;const execute=Q.execute,run=K.run,calculate=K.calculate;Q.execute=()=>{runs++;throw Error('implicit constructor');};K.run=()=>{runs++;throw Error('implicit task');};K.calculate=(op:string,...args:unknown[])=>{if(op==='action'){actions++;throw Error('implicit action');}return calculate(op,...args);};
 let c;try{c=ready(r,i);assert.throws(()=>r.inspect(c.child.id),code('unknown-artifact'));const f=r.offspringFrame({input:i,candidateId:c.candidateId,childSourceHash:c.childSourceHash,phase:.3,options:{budget:4000,crests:2}});assert.equal(f.frame.points.length,16000);assert.deepEqual(f.frame.nodeIds,c.child.graph.nodes.map(n=>n.id));assert.deepEqual([...new Set(f.frame.owners)].sort((a,b)=>a-b),f.frame.nodeIds.map((_,n)=>n));assert.equal(r.lineage().derivations.length,0);const ack=r.offspringAdmit({input:i,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'library'},requestId:'manual-child'});assert.equal(ack.artifactId,c.child.id);assert.equal(r.lineage({artifactId:ack.artifactId}).derivations.length,1);}finally{Q.execute=execute;K.run=run;K.calculate=calculate;}
 assert.equal(runs,0);assert.equal(actions,0);assert(c);assert.deepEqual(r.run(c.child.id).result.tasks[0]!.output,[{allocated:12,remaining:8}]);assert.throws(()=>r.run(c.child.id),code('resource-limit'));
 for(const recovery of [{source:c.child.source},{harmonics:c.child.harmonics},{colors:c.child.colors}]){const fresh=new Runtime(),child=fresh.recover(recovery);assert.equal(child.intent,undefined);assert.equal(child.design.heredity?.parents.length,2);assert.deepEqual(fresh.lineage({artifactId:child.id}).derivations,[]);const run=fresh.run(child.id);assert.deepEqual(run.result.tasks[0]!.output,[{allocated:12,remaining:8}]);assert.equal(fresh.reproduce(child.id,run.id).record.result.emitted[0],child.source);}
});

test('atomic world birth checks actual proposal parents, charges once and retries before stale revision',()=>{
 const r=new Runtime(),[a,b]=parents(r);let w=proposal(r,a,b);const p=w.proposals[0]!,i=input(a,b);i.origin={kind:'pairing',worldId:w.id,proposalId:p.id,parentResidents:p.parentResidents,epochs:p.epochs};const c=ready(r,i),request={input:i,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'world',worldId:w.id,expectedRevision:w.revision} as const,requestId:'world-birth'},before=structuredClone(w);const ack=r.offspringAdmit(request);w=r.worldInspect(w.id);assert.equal(w.revision,before.revision+1);assert.equal(w.residents.length,3);assert.equal(w.proposals.length,0);for(let n=0;n<2;n++)assert.equal(w.residents[n]!.energy,before.residents[n]!.energy-30);const child=w.residents.find(x=>x.id===ack.residentId)!;assert.equal(child.energy,40);assert.equal(child.enabled,false);assert.equal(child.nurseryUntil,w.tick+200);assert.deepEqual(r.offspringAdmit(request),ack);assert.deepEqual(r.worldInspect(w.id),w);
 assert.throws(()=>r.offspringAdmit({...request,requestId:'different-key'}),code('stale-state'));assert.throws(()=>r.offspringAdmit({...request,childSourceHash:'0'.repeat(64)}),code('metadata-conflict'));assert.deepEqual(r.worldInspect(w.id),w);assert.equal(r.lineage().derivations.length,1);
});

test('failed birth leaves world, source capacity, evidence and both charges untouched',()=>{
 const r=new Runtime({maxArtifacts:2}),[a,b]=parents(r),w=proposal(r,a,b),p=w.proposals[0]!,i=input(a,b);i.origin={kind:'pairing',worldId:w.id,proposalId:p.id,parentResidents:p.parentResidents,epochs:p.epochs};const c=ready(r,i),request={input:i,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'world',worldId:w.id,expectedRevision:w.revision} as const,requestId:'failed-birth'};assert.throws(()=>r.offspringAdmit(request),code('resource-limit'));assert.deepEqual(r.worldInspect(w.id),w);assert.equal(r.lineage().derivations.length,0);assert.throws(()=>r.inspect(c.child.id),code('unknown-artifact'));assert.throws(()=>r.offspringAdmit(request),code('resource-limit'));assert.deepEqual(r.worldInspect(w.id),w);
});

test('wrong social construction parents and withdrawn policies reject without admission',()=>{
 const r=new Runtime(),[a,b]=parents(r),w=proposal(r,a,b),p=w.proposals[0]!,wrong=r.create('mean [3,9] L');assert.equal(wrong.status,'supported');if(wrong.status!=='supported')throw Error('fixture');const i=input(a,b);i.parents[0]={artifactId:wrong.artifact.id,intentHash:O.intentHash(wrong.artifact.intent)};i.recipe={kind:'compose',donorOutput:wrong.artifact.graph.outputs[0]!,recipientInput:b.graph.nodes.find(n=>n.params.value===5)!.id};i.origin={kind:'pairing',worldId:w.id,proposalId:p.id,parentResidents:p.parentResidents,epochs:p.epochs};const rejected=r.offspringPreview(i); // Whether type fits cannot authorize unrelated social parents.
 assert.equal(rejected.status,'ready');if(rejected.status!=='ready')throw Error('wrong-parent fixture must be type-compatible');assert.throws(()=>r.offspringAdmit({input:i,candidateId:rejected.candidate.candidateId,childSourceHash:rejected.candidate.childSourceHash,target:{kind:'world',worldId:w.id,expectedRevision:w.revision},requestId:'wrong-parents'}),code('stale-state'));assert.equal(r.lineage().derivations.length,0);
 assert.deepEqual(r.worldInspect(w.id),w);const good=input(a,b);good.origin={kind:'pairing',worldId:w.id,proposalId:p.id,parentResidents:p.parentResidents,epochs:p.epochs};const c=ready(r,good),withdrawn=cmd(r,w,{kind:'participate',residentId:p.parentResidents[0],enabled:false});assert.throws(()=>r.offspringAdmit({input:good,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'world',worldId:w.id,expectedRevision:withdrawn.revision},requestId:'withdrawn'}),code('stale-state'));assert.deepEqual(r.worldInspect(w.id),withdrawn);
});

test('annotation after recovery preserves exact task and invalidates matching resident pins atomically',()=>{
 const original=new Runtime(),[a,b]=parents(original),r=new Runtime(),recovered=r.recover({source:a.source});let w=r.worldCreate({worldKey:'annotation',seed:1});w=cmd(r,w,{kind:'import',artifactId:recovered.id});const before=w.residents[0]!,enriched=r.annotate({artifactId:recovered.id,intent:a.intent!}),after=r.worldInspect(w.id);assert.deepEqual(enriched.intent,a.intent);assert.equal(after.revision,w.revision+1);assert.equal(after.residents[0]!.epoch,before.epoch+1);assert.equal(after.residents[0]!.intentHash,O.intentHash(a.intent));assert.deepEqual(r.annotate({artifactId:recovered.id,intent:a.intent!}),enriched);assert.deepEqual(r.worldInspect(w.id),after);assert.throws(()=>r.annotate({artifactId:recovered.id,intent:b.intent!}),code('metadata-conflict'));assert.deepEqual(r.worldInspect(w.id),after);
});

test('strict SDK and adapter schemas reject nested unknowns, getters and bounded field violations',()=>{
 const r=new Runtime(),[a,b]=parents(r),i=input(a,b),c=ready(r,i);assert(OffspringInputSchema.safeParse(i).success);for(const bad of [{...i,extra:true},{...i,style:{...i.style,extra:1}},{...i,recipe:{...i.recipe,extra:1}},{...i,origin:{kind:'manual',extra:1}},{...i,nonce:4294967296}]){assert.equal(OffspringInputSchema.safeParse(bad).success,false);assert.throws(()=>r.offspringPreview(bad as OffspringInput),code('invalid-input'));}
 let touched=0;const bad=Object.defineProperty({...i},'nonce',{enumerable:true,get(){touched++;return 0;}});assert.throws(()=>r.offspringPreview(bad),code('invalid-input'));assert.equal(touched,0);assert.equal(WorldCommandSchema.safeParse({worldId:'x',expectedRevision:0,sequence:1,command:{kind:'advance',ticks:5}}).success,false);assert.equal(AdmissionSchema.safeParse({input:i,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'library',expectedRevision:0},requestId:'x'}).success,false);assert.throws(()=>r.offspringFrame({input:i,candidateId:c.candidateId,childSourceHash:'0'.repeat(64),phase:0}),code('stale-state'));
 const view=r.offspringPreview({...i,parents:[{...i.parents[0],intentHash:'0'.repeat(64)},i.parents[1]]});assert.equal(view.status,'rejected');assert.equal(r.lineage().derivations.length,0);
});

test('legacy compile enrichment updates resident interpretation epoch through the same atomic preparation path',()=>{
 const original=new Runtime(),[a]=parents(original),r=new Runtime(),recovered=r.recover({source:a.source});let w=r.worldCreate({worldKey:'compile-enrich',seed:1});w=cmd(r,w,{kind:'import',artifactId:recovered.id});const enriched=r.compile(a.intent!,{seed:a.design.anatomy!.seed});assert.equal(enriched.id,a.id);const after=r.worldInspect(w.id);assert.equal(after.revision,w.revision+1);assert.equal(after.residents[0]!.epoch,w.residents[0]!.epoch+1);assert.equal(after.residents[0]!.intentHash,O.intentHash(a.intent));
});

test('malformed nullable option/target/command paths give typed refusals without state changes',()=>{
 const r=new Runtime(),[a,b]=parents(r),i=input(a,b),c=ready(r,i),w=r.worldCreate({worldKey:'nulls',seed:1});for(const call of [()=>r.offspringAdmit({input:i,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:null,requestId:'x'} as any),()=>r.worldCommand({worldId:w.id,expectedRevision:w.revision,sequence:w.nextSequence,command:null} as any),()=>r.worldCreate({worldKey:'nulls',seed:1,affinity:null} as any),()=>r.lineage({cursor:null} as any),()=>r.lineage({limit:null} as any)])assert.throws(call,code('invalid-input'));assert.deepEqual(r.worldInspect(w.id),w);assert.equal(r.lineage().derivations.length,0);
});

test('successful admission ledger never evicts replay protection when full',()=>{
 const r=new Runtime(),[a,b]=parents(r),i=input(a,b),c=ready(r,i),request={input:i,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'library'} as const,requestId:'receipt-0'},first=r.offspringAdmit(request);for(let n=1;n<128;n++)r.offspringAdmit({...request,requestId:'receipt-'+n});assert.equal(r.lineage().derivations.length,1);assert.deepEqual(r.offspringAdmit(request),first);assert.throws(()=>r.offspringAdmit({...request,requestId:'receipt-128'}),code('resource-limit'));assert.throws(()=>r.offspringAdmit({...request,input:{...i,nonce:i.nonce+1}}),code('metadata-conflict'));assert.deepEqual(r.offspringAdmit(request),first);
});

test('aggregate artifact byte limit is enforced before count capacity and preserves old source',()=>{
 const r=new Runtime({maxArtifacts:1024}),intent={format:'quineling-intent',name:'byte-bound',thought:'Supplied long literal',inputs:[{id:'value',value:'x'.repeat(16384),type:{kind:'string'}}],steps:[],outputs:['value']} as const;let sum=0,count=0,first:Artifact|undefined,refused=false;for(let seed=0;seed<1024;seed++){try{const a=r.compile(intent as any,{seed});first??=a;sum+=Buffer.byteLength(JSON.stringify(a));count++;}catch(e){assert(code('resource-limit')(e));refused=true;break;}}assert(refused);assert(count>0&&count<1024);assert(sum<=33554432);assert(first);assert.equal(r.inspect(first.id).source,first.source);assert.equal(r.lineage().derivations.length,0);
});


test('world birth plus first child companion attachment updates existing resident once within one revision',()=>{
 const r=new Runtime(),[a,b]=parents(r);let w=proposal(r,a,b);const p=w.proposals[0]!,i=input(a,b);i.origin={kind:'pairing',worldId:w.id,proposalId:p.id,parentResidents:p.parentResidents,epochs:p.epochs};const c=ready(r,i);
 const recovered=r.recover({source:c.child.source});assert.equal(recovered.intent,undefined);w=cmd(r,w,{kind:'import',artifactId:recovered.id});const old=w.residents.find(x=>x.artifactId===recovered.id)!;assert.equal(old.intentHash,null);
 const ack=r.offspringAdmit({input:i,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'world',worldId:w.id,expectedRevision:w.revision},requestId:'compound-enrichment'}),after=r.worldInspect(w.id);
 assert.equal(after.revision,w.revision+1);assert.equal(after.residents.length,4);const enriched=after.residents.find(x=>x.id===old.id)!;assert.equal(enriched.epoch,old.epoch+1);assert.equal(enriched.intentHash,O.intentHash(c.child.intent));assert.equal(after.residents.find(x=>x.id===ack.residentId)!.intentHash,enriched.intentHash);assert.equal(r.lineage().derivations.length,1);assert(r.inspect(recovered.id).intent);
});


test('inherited array getters reject before evaluation in direct Runtime and offspring boundaries',()=>{
 const r=new Runtime(),[a,b]=parents(r),i=input(a,b);let touched=0;const proto=Object.create(Array.prototype);Object.defineProperty(proto,'forEach',{get(){touched++;return Array.prototype.forEach;}});Object.setPrototypeOf(i.parents,proto);
 assert.throws(()=>r.offspringPreview(i),code('invalid-input'));assert.throws(()=>O.build([a,b],i),(e:any)=>e.code==='invalid-input');assert.equal(touched,0);assert.equal(r.lineage().derivations.length,0);
});
