import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash,randomUUID} from 'node:crypto';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {InMemoryTransport} from '@modelcontextprotocol/sdk/inMemory.js';
import {DefaultExecutionEventBus,RequestContext,ServerCallContext} from '@a2a-js/sdk/server';
import {SendMessageRequest,TaskState} from '@a2a-js/sdk';
import {Runtime,type Intent,type Artifact,type OffspringInput,type WorldAction,type World} from '../src/index.js';
import {createQuinelingMcpServer} from '../src/mcp.js';
import {createA2AApp,QuinelingExecutor} from '../src/a2a.js';
// @ts-expect-error shared JavaScript runtime has no declarations
import Q from '../../../core.js';

const canon=(v:any):string=>Array.isArray(v)?'['+v.map(canon).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canon(v[k])).join(',')+'}':JSON.stringify(v);
const hash=(v:any)=>createHash('sha256').update(canon(v)).digest('hex');
const pin=(a:Artifact)=>({artifactId:a.id,intentHash:a.intent?hash(a.intent):null});
const qty={kind:'number',unit:'L'} as const;
const reservoir:Intent={format:'quineling-intent',name:'Adapter reservoir',thought:'Average supplied litre readings.',inputs:[{id:'readings',value:[10,20,30],type:{kind:'array',element:qty}}],steps:[{id:'mean',op:'mean',inputs:['readings'],params:{}}],outputs:['mean'],assumptions:[]};
const budget:Intent={format:'quineling-intent',name:'Adapter budget',thought:'Budget supplied litres.',inputs:[{id:'available',value:5,type:qty},{id:'desired',value:12,type:qty}],steps:[{id:'budget',op:'budget',inputs:['available','desired'],params:{}}],outputs:['budget'],assumptions:[]};
const inputFor=(a:Artifact,b:Artifact):OffspringInput=>({parents:[pin(a),pin(b)],recipe:{kind:'compose',donorOutput:'mean',recipientInput:'available'},nonce:42,style:{mutation:'none'},origin:{kind:'manual'}});
function decoded(r:Awaited<ReturnType<Client['callTool']>>):any{assert.notEqual(r.isError,true,JSON.stringify(r.content));const data=r.structuredContent as any;assert.deepEqual(r.content,[{type:'text',text:JSON.stringify(data)}]);return data.result;}
function mcpError(r:Awaited<ReturnType<Client['callTool']>>,code:string){assert.equal(r.isError,true);const data=r.structuredContent as any;assert.equal(data.error.code,code);assert.equal(typeof data.error.path,'string');assert.ok(data.error.message);assert.deepEqual(r.content,[{type:'text',text:JSON.stringify(data)}]);}
function spyExecution(){const old=Q.execute;let calls=0;Q.execute=(...args:any[])=>{calls++;return old(...args);};return {calls:()=>calls,restore:()=>{Q.execute=old;}};}
async function withMcp(runtime:Runtime,fn:(client:Client,server:ReturnType<typeof createQuinelingMcpServer>,transports:ReturnType<typeof InMemoryTransport.createLinkedPair>)=>Promise<void>){const server=createQuinelingMcpServer(runtime),client=new Client({name:'ranch-tests',version:'0'}),transports=InMemoryTransport.createLinkedPair();await server.connect(transports[1]);await client.connect(transports[0]);try{await fn(client,server,transports);}finally{await client.close();await server.close();}}

const toolNames=['parse','compile','create','inspect','run','reproduce','recover','frame','offspring_preview','offspring_frame','offspring_admit','lineage','annotate','world_create','world_inspect','world_command'].map(s=>'quineling_'+s).sort();
test('official MCP discovers sixteen tools with strict nested ranch schemas and truthful annotations',async()=>{
 await withMcp(new Runtime(),async client=>{const tools=(await client.listTools()).tools;assert.deepEqual(tools.map(t=>t.name).sort(),toolNames);const named=(s:string)=>tools.find(t=>t.name==='quineling_'+s)!;
  const schema=named('offspring_preview').inputSchema as any,input=schema.properties.input;assert.equal(schema.additionalProperties,false);assert.equal(input.additionalProperties,false);assert.deepEqual([...input.required].sort(),['parents','recipe','nonce','style','origin'].sort());
  const recipes=input.properties.recipe.oneOf;assert.deepEqual(recipes.map((r:any)=>r.properties.kind.const).sort(),['body','compose','mate','merge']);for(const r of recipes)assert.equal(r.additionalProperties,false);assert.deepEqual(recipes.find((r:any)=>r.properties.kind.const==='compose').required,['kind','donorOutput','recipientInput']);
  assert.equal(input.properties.style.additionalProperties,false);const traits=input.properties.style.properties.traits;assert.equal(traits.additionalProperties,false);assert.equal(traits.properties.tempo.minimum,-1000);assert.equal(traits.properties.tempo.maximum,1000);
  const parent=input.properties.parents.items[0];assert.equal(input.properties.parents.minItems,2);assert.equal(input.properties.parents.maxItems,2);assert.equal(input.properties.parents.additionalItems,false);assert.equal(parent.additionalProperties,false);assert.deepEqual(parent.required,['artifactId','intentHash']);assert.ok(parent.properties.intentHash.anyOf.some((v:any)=>v.type==='null'));
  const pairing=input.properties.origin.oneOf.find((r:any)=>r.properties.kind.const==='pairing');assert.equal(pairing.additionalProperties,false);assert.equal(pairing.properties.parentResidents.minItems,2);assert.equal(pairing.properties.parentResidents.maxItems,2);
  const admission=named('offspring_admit').inputSchema as any;assert.equal(admission.additionalProperties,false);assert.deepEqual(admission.properties.target.oneOf.map((r:any)=>r.properties.kind.const),['library','world']);
  const command=named('world_command').inputSchema as any;assert.equal(command.additionalProperties,false);assert.deepEqual(command.properties.command.oneOf.map((r:any)=>r.properties.kind.const).sort(),['advance','cancelProposal','import','invite','participate','retire']);
  for(const name of ['offspring_preview','offspring_frame','lineage','world_inspect'])assert.equal(named(name).annotations?.readOnlyHint,true);for(const name of ['offspring_admit','annotate','world_create','world_command'])assert.equal(named(name).annotations?.readOnlyHint,false);assert.equal(named('world_command').annotations?.destructiveHint,true);assert.equal(named('offspring_admit').annotations?.idempotentHint,true);assert.equal(named('run').annotations?.idempotentHint,false);
 });
});

test('MCP useful offspring preview/frame/library/world admission remains passive before explicit source-independent Run',async()=>{
 const runtime=new Runtime({maxRecords:1}),spy=spyExecution();try{await withMcp(runtime,async client=>{
  const raw=(name:string,args:any)=>client.callTool({name:'quineling_'+name,arguments:args}),call=async(name:string,args:any={})=>decoded(await raw(name,args));
  const a=await call('compile',{intent:reservoir,options:{seed:17}}) as Artifact,b=await call('compile',{intent:budget,options:{seed:23,repeats:3}}) as Artifact,input=inputFor(a,b),preview=await call('offspring_preview',{input});assert.equal(preview.status,'ready');const c=preview.candidate;
  assert.deepEqual(await call('lineage'),{derivations:[]});mcpError(await raw('inspect',{artifactId:c.child.id}),'unknown-artifact');
  const frame=await call('offspring_frame',{input,candidateId:c.candidateId,childSourceHash:c.childSourceHash,phase:0,options:{budget:4000,crests:2}});assert.equal(frame.frame.owners.length,4000);assert.equal(frame.frame.points.length,16000);assert.equal(new Set(frame.frame.owners).size,c.child.graph.nodes.length);
  mcpError(await raw('offspring_frame',{input,candidateId:c.candidateId,childSourceHash:'0'.repeat(64),phase:0}),'stale-state');
  const req={input,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'library' as const},requestId:'mcp-library'},ack=await call('offspring_admit',req);assert.deepEqual(await call('offspring_admit',req),ack);const stored=await call('inspect',{artifactId:ack.artifactId});assert.equal(stored.source,c.child.source);
  const lineage=await call('lineage',{artifactId:ack.artifactId});assert.equal(lineage.derivations.length,1);assert.equal(lineage.derivations[0].id,ack.derivationId);mcpError(await raw('offspring_admit',{...req,input:{...input,nonce:43}}),'metadata-conflict');assert.deepEqual(await call('lineage'),lineage);
  const stale=structuredClone(input);stale.parents[0].intentHash='0'.repeat(64);const refused=await call('offspring_preview',{input:stale});assert.equal(refused.status,'rejected');assert.equal(refused.diagnostics[0].code,'stale-state');
  assert.equal((await raw('offspring_preview',{input:{...input,style:{mutation:'none',admin:true}}})).isError,true);
  const wrongUnit=structuredClone(reservoir);(wrongUnit.inputs[0]!.type as any).element.unit='s';const wrong=await call('compile',{intent:wrongUnit}),incompatible=await call('offspring_preview',{input:inputFor(wrong,b)});assert.equal(incompatible.status,'rejected');assert.equal(incompatible.diagnostics[0].code,'invalid-offspring');
  const sourceOnlyPreview=await call('offspring_preview',{input:{...input,nonce:99}}),bare=await call('recover',{source:sourceOnlyPreview.candidate.child.source});assert.equal(bare.intent,undefined);const annotated=await call('annotate',{artifactId:bare.id,intent:sourceOnlyPreview.candidate.child.intent});assert.deepEqual(annotated.intent,sourceOnlyPreview.candidate.child.intent);const conflict=structuredClone(annotated.intent);conflict.thought='Conflicting interpretation';mcpError(await raw('annotate',{artifactId:bare.id,intent:conflict}),'metadata-conflict');assert.equal((await call('inspect',{artifactId:bare.id})).intent.thought,annotated.intent.thought);
  const w=await call('world_create',{worldKey:'mcp-ranch',seed:23,affinity:'neutral'});assert.deepEqual(await call('world_create',{worldKey:'mcp-ranch',seed:23,affinity:'neutral'}),w);const inspect=async()=>await call('world_inspect',{worldId:w.id}) as World;
  const command=async(action:WorldAction)=>{const s=await inspect(),request={worldId:w.id,expectedRevision:s.revision,sequence:s.nextSequence,command:action},ack=await call('world_command',request);assert.deepEqual(await call('world_command',request),ack);return ack;};
  const p0=(await command({kind:'import',artifactId:a.id})).residentId,p1=(await command({kind:'import',artifactId:b.id})).residentId;await command({kind:'participate',residentId:p0,enabled:true});await command({kind:'participate',residentId:p1,enabled:true});await command({kind:'invite',residentId:p0,partnerId:p1});await command({kind:'invite',residentId:p1,partnerId:p0});
  let s=await inspect();for(let i=0;i<200&&!s.proposals.some(p=>p.parentResidents.every(id=>s.residents.find(r=>r.id===id)!.energy>=50));i++){await command({kind:'advance',ticks:4});s=await inspect();}
  const proposal=s.proposals[0]!;assert.ok(proposal);const pairInput:OffspringInput={...input,parents:proposal.artifactIds.map((artifactId,i)=>({artifactId,intentHash:proposal.intentHashes[i]!})) as OffspringInput['parents'],origin:{kind:'pairing',worldId:w.id,proposalId:proposal.id,parentResidents:proposal.parentResidents,epochs:proposal.epochs}},paired=await call('offspring_preview',{input:pairInput});assert.equal(paired.status,'ready');assert.equal(paired.candidate.child.source,c.child.source);
  const birthRequest={input:pairInput,candidateId:paired.candidate.candidateId,childSourceHash:paired.candidate.childSourceHash,target:{kind:'world',worldId:w.id,expectedRevision:s.revision},requestId:'mcp-birth'},wrongEpoch=structuredClone(birthRequest);(wrongEpoch.input.origin as any).epochs[0]++;wrongEpoch.requestId='mcp-wrong-epoch';mcpError(await raw('offspring_admit',wrongEpoch),'stale-state');assert.deepEqual(await inspect(),s);const wrongProposal=structuredClone(birthRequest);(wrongProposal.input.origin as any).proposalId='missing-proposal';wrongProposal.requestId='mcp-wrong-proposal';mcpError(await raw('offspring_admit',wrongProposal),'stale-state');const wrongParents=structuredClone(birthRequest);wrongParents.input.parents.reverse();wrongParents.requestId='mcp-wrong-parents';mcpError(await raw('offspring_admit',wrongParents),'stale-state');assert.deepEqual(await inspect(),s);
  const born=await call('offspring_admit',birthRequest),after=await inspect();assert.equal(after.residents.length,s.residents.length+1);assert.equal(after.revision,s.revision+1);assert.equal(after.proposals.length,0);for(const id of proposal.parentResidents)assert.equal(after.residents.find(r=>r.id===id)!.energy,s.residents.find(r=>r.id===id)!.energy-30);const nursery=after.residents.find(r=>r.id===born.residentId)!;assert.equal(nursery.energy,40);assert.equal(nursery.enabled,false);assert.equal(nursery.nurseryUntil,s.tick+200);
  assert.deepEqual(await call('offspring_admit',birthRequest),born);assert.deepEqual(await inspect(),after);mcpError(await raw('offspring_admit',{...birthRequest,requestId:'mcp-consumed-new-key'}),'stale-state');assert.deepEqual(await inspect(),after);assert.equal((await call('lineage',{artifactId:born.artifactId})).derivations.length,2);
  assert.equal(spy.calls(),0,'All passive paths created zero constructor executions');const run=await call('run',{artifactId:born.artifactId});assert.deepEqual(run.result.tasks[0].output,[{allocated:12,remaining:8}]);assert.equal(run.result.tasks.length,1);assert.equal(run.result.tasks[0].effects.length,0);assert.equal(run.result.emitted[0],c.child.source);assert.equal(spy.calls(),1);mcpError(await raw('run',{artifactId:born.artifactId}),'resource-limit');
  const freshRuntime=new Runtime({maxRecords:1}),recovered=freshRuntime.recover({source:stored.source});assert.equal(recovered.intent,undefined);assert.deepEqual(freshRuntime.run(recovered.id).result.tasks[0]!.output,[{allocated:12,remaining:8}]);
 });}finally{spy.restore();}
});

test('official MCP same-turn admission cancellation skips stores and defensive pre-cancel returns structured error',async()=>{
 const runtime=new Runtime(),a=runtime.compile(reservoir),b=runtime.compile(budget),input=inputFor(a,b),preview=runtime.offspringPreview(input);if(preview.status!=='ready')throw Error('Fixture refused');const c=preview.candidate,request={input,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'library' as const},requestId:'cancelled-admission'};
 await withMcp(runtime,async(_client,server,[clientTransport,serverTransport])=>{const outgoing:unknown[]=[],send=serverTransport.send.bind(serverTransport);serverTransport.send=async(message,options)=>{if('id'in message&&message.id===900001)outgoing.push(message);await send(message,options);};
  const sent=clientTransport.send({jsonrpc:'2.0',id:900001,method:'tools/call',params:{name:'quineling_offspring_admit',arguments:request}}),cancel=clientTransport.send({jsonrpc:'2.0',method:'notifications/cancelled',params:{requestId:900001,reason:'Cancel before dispatch'}});await Promise.all([sent,cancel]);await new Promise<void>(resolve=>setImmediate(resolve));assert.deepEqual(outgoing,[]);assert.deepEqual(runtime.lineage(),{derivations:[]});assert.throws(()=>runtime.inspect(c.child.id));
  type Handler=(args:unknown,extra:{signal:AbortSignal})=>Promise<Awaited<ReturnType<Client['callTool']>>>;const handler=(server as unknown as {_registeredTools:Record<string,{handler:Handler}>})._registeredTools.quineling_offspring_admit!.handler,abort=new AbortController();abort.abort();mcpError(await handler(request,{signal:abort.signal}),'cancelled');const live=new AbortController();mcpError(await handler({...request,input:{...input,style:{mutation:'none',unknown:1}}},{signal:live.signal}),'invalid-input');assert.deepEqual(runtime.lineage(),{derivations:[]});assert.equal(runtime.offspringAdmit(request).artifactId,c.child.id);
 });
});

async function httpFixture(runtime:Runtime){const http=createServer();http.listen(0,'127.0.0.1');await once(http,'listening');const addr=http.address();assert(addr&&typeof addr==='object');const base=`http://127.0.0.1:${addr.port}`,instance=createA2AApp({runtime,baseUrl:base});http.on('request',instance.app);return {base,...instance,close:()=>new Promise<void>((resolve,reject)=>http.close(e=>e?reject(e):resolve()))};}
async function rpc(base:string,method:string,params:unknown):Promise<any>{const r=await fetch(base+'/a2a/jsonrpc',{method:'POST',headers:{'content-type':'application/json','A2A-Version':'1.0'},body:JSON.stringify({jsonrpc:'2.0',id:randomUUID(),method,params}),signal:AbortSignal.timeout(10000)});assert.equal(r.status,200);return r.json();}
const message=(data:unknown,text=false)=>({message:{messageId:randomUUID(),role:'ROLE_USER',parts:[text?{text:data}:{data,mediaType:'application/json'}]}});
function a2aPayload(r:any,operation:string){assert(!r.error,JSON.stringify(r));const task=r.result.task;assert.equal(task.status.state,'TASK_STATE_COMPLETED',JSON.stringify(task.status));const data=task.artifacts.at(-1).parts[0].data;assert.equal(data.operation,operation);return data.result;}
function a2aError(r:any,code:string){assert(!r.error);assert.equal(r.result.task.status.state,'TASK_STATE_FAILED');assert.ok(!r.result.task.artifacts?.length);const e=r.result.task.status.message.metadata.quinelingError;assert.equal(e.code,code);assert.equal(typeof e.path,'string');assert.ok(e.message);return e;}

test('real A2A HTTP ranch skill and structured passive offspring/world requests preserve envelopes, retries, errors and useful Run',async()=>{
 const runtime=new Runtime({maxRecords:1}),s=await httpFixture(runtime),spy=spyExecution();try{
  const card=await(await fetch(s.base+'/.well-known/agent-card.json',{headers:{'A2A-Version':'1.0'}})).json() as any;assert.deepEqual(card.skills.map((x:any)=>x.id).sort(),['build','execute','ranch']);assert.deepEqual(card.skills.find((x:any)=>x.id==='ranch').inputModes,['application/json']);
  const send=(r:any)=>rpc(s.base,'SendMessage',message(r)),call=async(operation:string,args:any={})=>a2aPayload(await send({operation,...args}),operation);
  const made=a2aPayload(await rpc(s.base,'SendMessage',message('[2,3,4] | square | sum',true)),'create');assert.equal(made.status,'supported');assert.equal(made.record,undefined);
  const a=await call('compile',{intent:reservoir,options:{seed:17}}),b=await call('compile',{intent:budget,options:{seed:23}}),input=inputFor(a,b),preview=await call('offspringPreview',{input});assert.equal(preview.status,'ready');const c=preview.candidate;
  const frame=await call('offspringFrame',{input,candidateId:c.candidateId,childSourceHash:c.childSourceHash,phase:0,options:{budget:4000,crests:2}});assert.equal(frame.frame.owners.length,4000);assert.deepEqual(await call('lineage'),{derivations:[]});
  const admission={input,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'library' as const},requestId:'a2a-library'},ack=await call('offspringAdmit',admission);assert.deepEqual(await call('offspringAdmit',admission),ack);assert.equal((await call('lineage',{artifactId:ack.artifactId})).derivations.length,1);
  const conflict=await send({operation:'offspringAdmit',...admission,input:{...input,nonce:43}}),diagnostic=a2aError(conflict,'metadata-conflict'),fetched=await rpc(s.base,'GetTask',{id:conflict.result.task.id});assert.deepEqual(fetched.result.status.message.metadata.quinelingError,diagnostic);
  const stale=structuredClone(input);stale.parents[0].intentHash='0'.repeat(64);const refused=await call('offspringPreview',{input:stale});assert.equal(refused.status,'rejected');assert.equal(refused.diagnostics[0].code,'stale-state');a2aError(await send({operation:'offspringFrame',input,candidateId:c.candidateId,childSourceHash:'0'.repeat(64),phase:0}),'stale-state');a2aError(await send({operation:'offspringPreview',input:{...input,recipe:{...input.recipe,provider:'root'}}}),'invalid-input');
  const barePreview=await call('offspringPreview',{input:{...input,nonce:98}}),bare=await call('recover',{recovery:{source:barePreview.candidate.child.source}});assert.equal(bare.intent,undefined);assert.deepEqual((await call('annotate',{artifactId:bare.id,intent:barePreview.candidate.child.intent})).intent,barePreview.candidate.child.intent);
  const world=await call('worldCreate',{worldKey:'a2a-ranch',seed:23,affinity:'neutral'}),first={worldId:world.id,expectedRevision:world.revision,sequence:world.nextSequence,command:{kind:'import',artifactId:a.id}},imported=await call('worldCommand',first);assert.deepEqual(await call('worldCommand',first),imported);const before=await call('worldInspect',{worldId:world.id});
  a2aError(await send({operation:'worldCommand',...first,command:{kind:'import',artifactId:b.id}}),'invalid-offspring');assert.deepEqual(await call('worldInspect',{worldId:world.id}),before);const participated=await call('worldCommand',{worldId:world.id,expectedRevision:before.revision,sequence:before.nextSequence,command:{kind:'participate',residentId:imported.residentId,enabled:true}});assert.equal(participated.revision,before.revision+1);assert.equal((await call('worldInspect',{worldId:world.id})).residents[0].enabled,true);
  const inspectWorld=async()=>await call('worldInspect',{worldId:world.id}) as World;
  const worldCommand=async(command:WorldAction)=>{const s=await inspectWorld();return call('worldCommand',{worldId:world.id,expectedRevision:s.revision,sequence:s.nextSequence,command});};
  const second=(await worldCommand({kind:'import',artifactId:b.id})).residentId;await worldCommand({kind:'participate',residentId:second,enabled:true});await worldCommand({kind:'invite',residentId:imported.residentId,partnerId:second});await worldCommand({kind:'invite',residentId:second,partnerId:imported.residentId});
  let ws=await inspectWorld();for(let i=0;i<200&&!ws.proposals.some(p=>p.parentResidents.every(id=>ws.residents.find(r=>r.id===id)!.energy>=50));i++){await worldCommand({kind:'advance',ticks:4});ws=await inspectWorld();}
  const proposal=ws.proposals[0]!;assert.ok(proposal);const pairingInput:OffspringInput={...input,parents:proposal.artifactIds.map((artifactId,i)=>({artifactId,intentHash:proposal.intentHashes[i]!})) as OffspringInput['parents'],origin:{kind:'pairing',worldId:world.id,proposalId:proposal.id,parentResidents:proposal.parentResidents,epochs:proposal.epochs}},social=await call('offspringPreview',{input:pairingInput});assert.equal(social.status,'ready');assert.equal(social.candidate.child.source,c.child.source);
  const birthRequest={input:pairingInput,candidateId:social.candidate.candidateId,childSourceHash:social.candidate.childSourceHash,target:{kind:'world',worldId:world.id,expectedRevision:ws.revision},requestId:'a2a-world-birth'},birth=await call('offspringAdmit',birthRequest),afterBirth=await inspectWorld();assert.equal(afterBirth.revision,ws.revision+1);assert.equal(afterBirth.residents.length,ws.residents.length+1);for(const id of proposal.parentResidents)assert.equal(afterBirth.residents.find(r=>r.id===id)!.energy,ws.residents.find(r=>r.id===id)!.energy-30);assert.equal(afterBirth.residents.find(r=>r.id===birth.residentId)!.enabled,false);
  assert.deepEqual(await call('offspringAdmit',birthRequest),birth);assert.deepEqual(await inspectWorld(),afterBirth);a2aError(await send({operation:'offspringAdmit',...birthRequest,requestId:'a2a-consumed-new-key'}),'stale-state');assert.deepEqual(await inspectWorld(),afterBirth);assert.equal((await call('lineage',{artifactId:birth.artifactId})).derivations.length,2);

  assert.equal(spy.calls(),0,'HTTP text/preview/admit/world/annotate all remain passive');const stored=await call('inspect',{artifactId:ack.artifactId}),fresh=new Runtime({maxRecords:1}),recovered=fresh.recover({source:stored.source});assert.equal(recovered.intent,undefined);assert.deepEqual(fresh.run(recovered.id).result.tasks[0]!.output,[{allocated:12,remaining:8}]);
  const run=await call('run',{artifactId:ack.artifactId});assert.deepEqual(run.result.tasks[0].output,[{allocated:12,remaining:8}]);assert.equal(run.result.emitted[0],stored.source);a2aError(await send({operation:'run',artifactId:ack.artifactId}),'resource-limit');
 }finally{spy.restore();await s.close();}
});

test('A2A pre-dispatch structured-admission cancellation creates no artifact or derivation',async()=>{
 const runtime=new Runtime(),a=runtime.compile(reservoir),b=runtime.compile(budget),input=inputFor(a,b),preview=runtime.offspringPreview(input);if(preview.status!=='ready')throw Error('Fixture refused');const c=preview.candidate,request=SendMessageRequest.fromJSON(message({operation:'offspringAdmit',input,candidateId:c.candidateId,childSourceHash:c.childSourceHash,target:{kind:'library' as const},requestId:'a2a-cancel'})),executor=new QuinelingExecutor(runtime),bus=new DefaultExecutionEventBus(),states:TaskState[]=[],dispatch=runtime.dispatch.bind(runtime);let dispatches=0;runtime.dispatch=r=>{dispatches++;return dispatch(r);};bus.on('event',event=>{if(event.kind==='statusUpdate'&&event.data.status)states.push(event.data.status.state);});const running=executor.execute(new RequestContext(request,'cancel-ranch','context',new ServerCallContext()),bus);await executor.cancelTask('cancel-ranch',bus);await running;assert.equal(dispatches,0);assert.deepEqual(states,[TaskState.TASK_STATE_CANCELED]);assert.deepEqual(runtime.lineage(),{derivations:[]});assert.throws(()=>runtime.inspect(c.child.id));
});
